import { createContext, useContext, useState, type ReactNode } from 'react'

const TRANSLATIONS = {
  en: {
    // Nav
    dashboard:   'Dashboard',
    properties:  'Properties',
    watching:    'Watching',
    settings:    'Settings',
    logout:      'Logout',

    // Stats cards
    propertiesInArea:  'Properties in Area',
    newToday:          'New Today',
    strongOpps:        'Strong Opportunities',
    worthInvest:       'Worth Investigating',
    priceDrops:        'Price Drops Today',
    avgScore:          'Avg Score',

    // Score categories
    strongOpportunity:  'Strong Opportunity',
    worthInvestigating: 'Worth Investigating',
    marketPrice:        'Market Price',
    notRecommended:     'Not Recommended',

    // Actions
    viewAnalysis:       'View Analysis',
    watchProperty:      'Watch',
    reanalyze:          'Re-analyze',
    backToProperties:   'Back to properties',
    viewOnSource:       'View on',

    // Filters
    filters:       'Filters',
    sortBy:        'Sort by',
    allTypes:      'All types',
    allCities:     'All cities',
    minScore:      'Min score',
    anyScore:      'Any',
    gridView:      'Grid',
    listView:      'List',
    noResults:     'No properties match your filters.',
    noResultsHint: 'Try expanding your price range or area.',

    // Detail page tabs
    aiBrief:      'AI Brief',
    financials:   'Financials',
    comparables:  'Comparables',
    priceHistory: 'Price History',
    sources:      'Sources',

    // Financial labels
    askingPrice:    'Asking Price',
    marketValue:    'Market Value (comparable sales)',
    valueGap:       'Your savings vs market',
    discount:       'Below market price',
    capRate:        'Yearly return (cap rate)',
    cashFlow:       'Monthly profit (cash flow)',
    cashOnCash:     'Return on cash invested',
    noi:            'Net annual income',
    grm:            'Price/rent ratio (GRM)',
    downPayment:    'Your down payment (20%)',
    welcomeTax:     'Welcome tax (droits de mutation)',
    monthlyMortgage:'Monthly mortgage payment',
    rentalIncome:   'Monthly rental income',
    grossIncome:    'Annual gross income',
    municipalTax:   'Municipal property taxes',
    schoolTax:      'School taxes (annual)',
    condoFees:      'Monthly condo fees',
    pricePerSqft:   'Price per sqft',
    compsFound:     'Comparable sales found',

    // Misc
    units:       'units',
    sqft:        'sqft',
    built:       'Built',
    daysOnMarket:'days on market',
    newBadge:    'NEW',
    priceDrop:   'Price Drop',
    active:      'Active',
    topOpps:     'Top Opportunities',
    newListings: 'New Listings',
    coverage:    'Coverage',
    viewAll:     'View all →',
    notFound:    'Property not found',
    notFoundHint:'This listing may have been delisted or removed.',
    browseAll:   'Browse all properties →',
    queued:      'Queued',
    lastAnalyzed:'Last analyzed',
    firstSeen:   'First seen',
    lastChecked: 'Last checked',
    mlsNumber:   'MLS#',
    noPriceHistory:   'No price changes recorded.',
    noComparables:    'No comparables found for this property.',
    noSources:        'No active sources recorded.',
    noAiBrief:        'AI brief not yet generated.',
    noAiBriefLow:     'Score below 40 — brief not generated for this property.',
    runPipeline:      'Click Re-analyze to queue this property.',
    dealProfile:      'Deal Profile',
    confidencePill:   'confidence',
    analyzedUsing:    'analyzed',
    within:           'within',
    medianPrice:      'Median Price',
    meanPrice:        'Mean Price',
    pricedAt:         'Priced',
    belowMarket:      'below market',
    aboveMarket:      'above market',
    originalListing:  'Originally listed',
    totalReduction:   'Total reduction',
    fromOriginal:     'from original',
    settings_title:   'Settings',
    settings_subtitle:'Manage your account and notification preferences.',
    settings_saved:   'Preferences saved',

    // Multi-site comparison
    multiSite:        'Multi-site',
    multiSiteFilter:  'Multi-site only',
    lowestPrice:      'Lowest price',
    lowestPriceSite:  'Lowest price site',
    savingsVsHighest: 'Save vs highest',
    onSites:          'sites',
    priceComparison:  'Price Comparison',
    lastUpdated:      'Updated',

    // Nav (sidebar)
    nav_marketAlerts:    'Market Alerts',
    nav_savedSearches:   'Saved Searches',
    nav_reports:         'Reports',
    nav_savedProperties: 'Saved Properties',
    nav_adminDashboard:  'Admin Dashboard',

    // Settings — header
    set_headerSubtitle: 'Your investment preferences, saved to your account.',
    set_applyToSearch:  'Apply to search',
    set_save:           'Save preferences',
    set_saved:          'Saved',
    set_saving:         'Saving…',

    // Settings — search location
    set_location_title: 'Search location',
    set_location_desc:  "The cities you're hunting in — pick as many as you like.",
    set_targetCities:   'Target cities',
    set_addAnother:     'Add another…',
    set_cityPlaceholder:'e.g. Montréal, Laval…',
    set_add:            'Add',
    set_searchRadius:   'Search radius',

    // Settings — budget
    set_budget_title:   'Budget range',
    set_budget_desc:    'The price band you invest in.',
    set_budget_under:   'Under $300K',
    set_budget_300500:  '$300K – $500K',
    set_budget_500750:  '$500K – $750K',
    set_budget_7501m:   '$750K – $1M',
    set_budget_over1m:  'Over $1M',
    set_budget_custom:  'Custom',
    set_minPrice:       'Min price',
    set_maxPrice:       'Max price',
    set_any:            'Any',

    // Settings — property types
    set_types_title:    'Property types',
    set_types_desc:     "Pick every type you'd consider.",
    type_duplex:        'Duplex',
    type_triplex:       'Triplex',
    type_quadruplex:    'Quadruplex',
    type_quintuplex:    'Quintuplex+',
    type_single_family: 'Single Family',
    type_condo:         'Condo',
    units_2:            '2 units',
    units_3:            '3 units',
    units_4:            '4 units',
    units_5plus:        '5+ units',
    unit_house:         'house',
    unit_apartment:     'apartment',

    // Settings — investment goal
    set_goal_title:     'Investment goal',
    set_goal_desc:      'Pick the strategy (or both) you invest with.',
    goal_hold_label:    'Buy & Hold',
    goal_hold_desc:     'Monthly rental income from tenants',
    goal_hold_info:     'You keep the property long-term and rent it out. The goal is steady monthly cash flow plus long-term appreciation. With this strategy Your Verdict leans on cap rate and cash flow.',
    goal_flip_label:    'Flip (Fix & Sell)',
    goal_flip_desc:     'Buy cheap, renovate, sell for profit',
    goal_flip_info:     'You buy below market, renovate, and resell for a one-time profit — the spread between what you paid plus reno costs and the resale price. With this strategy Your Verdict leans on price discount and days-on-market (motivated sellers).',
    set_whatsThis:      "What's this?",

    // Settings — alerts
    set_alerts_title:   'Alert triggers',
    set_alerts_desc:    'What should trigger a notification.',
    set_newListings:    'New listings',
    set_newListings_sub:'A property matching your criteria appears',
    set_priceDrops:     'Price drops',
    set_priceDrops_sub: "A listing you'd want drops in price",
    set_minQuality:     'Min deal quality',
    set_qualityAny:     'Any',
    set_qualityGood:    'Good',
    set_qualityTop:     'Top',
    set_qualityBest:    'Best',

    // Settings — delivery
    set_delivery_title: 'Delivery channels',
    set_delivery_desc:  'How we reach you.',
    set_emailAlerts:    'Email alerts',
    set_sentTo:         'Sent to',
    set_sentToAccount:  'Sent to your account email',
    set_smsWhatsapp:    'SMS & WhatsApp',
    set_comingSoon:     'Coming soon',
    set_phoneNumber:    'Phone number',
    set_sms:            'SMS',
    set_sms_sub:        'Works on any phone',
    set_whatsapp:       'WhatsApp',
    set_whatsapp_sub:   'Rich messages with photos',
    set_phoneNeeded:    'Enter a valid phone number to enable SMS/WhatsApp.',

    // Settings — language
    set_language_title: 'Language',
    set_language_desc:  'Interface language.',

    // Settings — My Scoring Criteria
    set_scoring_title:  'My Scoring Criteria',
    set_scoring_desc:   'Set your buy box in real numbers. Properties that meet your targets are shown first and scored against your own numbers.',
    set_howThisWorks:   'How this works',
    set_yourBuyBox:     'Your buy box',
    set_inNumbers:      '— in numbers, not percentages',
    set_buyBoxHint:     'Set a target with the slider or by typing a number — leave it at Off to ignore it. Targets both filter the Properties list and raise a listing\'s score the more it beats your number.',
    set_advanced:       'Advanced — fine-tune how factors are weighted when ranking',
    set_reset:          'Reset',
    set_yourMix:        'Your mix',
    set_yourMix_desc:   'Each slider is independent. The donut shows the resulting share of your verdict.',
    set_topFactor:      'Top factor',
    set_off:            'Off',
    preset_balanced:    'Balanced',
    preset_cashflow:    'Cash-flow',
    preset_buyhold:     'Buy & Hold',
    preset_value:       'Value / Flip',
    preset_custom:      'Custom',
    factor_discount:    'Price Discount',
    factor_cap_rate:    'Cap Rate',
    factor_cash_flow:   'Cash Flow',
    factor_grm:         'GRM',
    factor_confidence:  'Confidence',
    factor_dom_bonus:   'Days Listed',
    factor_price_history:'Price Trend',
    factor_price_cut:   'Price Cut',
    fdesc_discount:     'How far below comparable sales it is priced',
    fdesc_cap_rate:     'Annual return — net income vs. purchase price',
    fdesc_cash_flow:    'Monthly profit after mortgage, taxes & expenses',
    fdesc_grm:          'Price relative to gross rent (lower is better)',
    fdesc_confidence:   'How much comparable data backs the numbers',
    fdesc_dom_bonus:    'Days on market — longer means more seller leverage',
    fdesc_price_cut:    'Price cut since listing — a motivated-seller signal',
    // Scoring "how this works" modal
    help_intro:         'Your Verdict ranks every property by your numbers instead of the app\'s default opinion. It works in three steps:',
    help_step1_title:   'Set your targets in real numbers',
    help_step2_title:   'Every listing is scored against your numbers',
    help_step3_title:   'The factors combine into Your Verdict',
    help_example:       'Example',
    help_note:          "One guardrail: when a listing's rent is only estimated (not disclosed by the seller), the income factors — cap rate, cash flow, GRM — can't score above neutral, so made-up rent can't inflate a verdict.",
    help_step1_body:    'Use the sliders (or type a number) for what matters — e.g. $200/mo cash flow and 30+ days on market. Leave the rest Off.',
    help_step2_body:    'Each factor scores 0–100. Meet or beat your target and it scores 100 — the more a listing beats your number, the higher it scores.',
    help_step3_body:    'Your targets (and any importance tweaks) blend into one 0–100 score, and the whole Properties list is ranked by it — not just one page.',
    help_example_body:  'A listing at $250/mo (target $200) that has been up 45 days (target 30) maxes out both factors — so it lands near the top of Your Verdict.',

    // Dashboard
    dash_subtitle:      'Quebec real estate investment overview',
    dash_newToday:      'New today',
    dash_m_total:       'Total properties',
    dash_m_total_sub:   'across Quebec',
    dash_m_new:         'New listings',
    dash_m_new_sub:     'added today',
    dash_m_great:       'Great deals',
    dash_m_great_sub:   'score 80+',
    dash_m_worth:       'Worth checking',
    dash_m_worth_sub:   'score 60–79',
    dash_m_drops:       'Price drops',
    dash_m_drops_sub:   'since yesterday',
    dash_m_avg:         'Avg deal score',
    dash_m_avg_sub:     'out of 100',
    dash_m_multi:       'Multi-site listings',
    dash_m_multi_sub:   'compare prices',
    dash_rankedYour:    'Ranked by your own scoring criteria',
    dash_bestNow:       'Best investment opportunities right now',
    dash_viewAll:       'View all',
    dash_noScored:      'No scored properties yet — run the AI pipeline to generate scores.',
    dash_recentlyAdded: 'Recently added to database',
    dash_noNewToday:    'No new listings recorded today.',
    dash_quickFilters:  'Quick Filters',
    dash_qf_new24:      'New last 24h',
    dash_qf_best:       'Best deals (80+)',
    dash_qf_drops:      'Price drops',
    dash_qf_multi:      'On multiple sites',
    dash_qf_yield:      'Highest yield',
    dash_topCities:     'Top Cities',
    dash_covered:       'covered',
    dash_moreCities:    'more cities',
    time_justNow:       'Just now',
    time_hAgo:          'h ago',
    time_dAgo:          'd ago',

    // Properties page
    ptype_duplex:       'Duplex (2 units)',
    ptype_triplex:      'Triplex (3 units)',
    ptype_quadruplex:   'Quadruplex (4 units)',
    ptype_quintuplex:   'Quintuplex+ (5+ units)',
    ptype_single:       'Single Family Home',
    ptype_condo:        'Condo',
    pf_quality_any:     'Any quality',
    pf_quality_great:   'Great deals only (80+)',
    pf_quality_worth:   'Worth checking (60+)',
    pf_quality_all:     'Show everything (40+)',
    pf_time_any:        'Any time',
    pf_time_24h:        'Last 24 hours',
    pf_time_48h:        'Last 48 hours',
    pf_time_7d:         'Last 7 days',
    pf_time_30d:        'Last 30 days',
    pf_sort_best:       'Best deals first',
    pf_sort_discount:   'Biggest discount first',
    pf_sort_priceasc:   'Lowest price first',
    pf_sort_pricedesc:  'Highest price first',
    pf_sort_newest:     'Newest listings first',
    pf_sort_longest:    'Longest listed first',
    pf_chip_24h:        'Last 24h',
    pf_chip_48h:        'Last 48h',
    pf_chip_7d:         'Last 7 days',
    pf_chip_30d:        'Last 30 days',
    pf_chip_best:       'Best deals',
    pf_chip_discount:   'Biggest discount',
    pf_chip_lowest:     'Lowest price',
    pf_chip_highest:    'Highest price',
    pf_searchPlaceholder:'Search address or city…',
    pf_mlsPlaceholder:  'MLS number…',
    pf_egMin:           'e.g. 300000',
    pf_egMax:           'e.g. 1000000',
    pf_of:              'of',
    pf_listingsMatch:   'listings match your criteria',
    pf_rankAI:          'AI',
    pf_rankMine:        'My Metrics',
    pf_clear:           'Clear',
    pf_clearAll:        'Clear all',
    pf_propertyType:    'Property Type',
    pf_minQuality:      'Minimum quality',
    pf_listedWithin:    'Listed within',
    pf_city:            'City',
    pf_minPrice:        'Min price ($)',
    pf_maxPrice:        'Max price ($)',
    pf_multiOnly:       'Listed on multiple sites',
    pf_sizeData:        'Size data',
    pf_hasSqft:         'Has sqft only',
    pf_floodRisk:       'Flood risk',
    pf_floodOnly:       'Flagged flood zone only',
    pf_noResults:       'No properties found',
    pf_noResultsHint:   'Try adjusting your filters or expanding the search area.',
    pf_clearAllFilters: 'Clear all filters',
    pf_buyBoxTitle:     'Your buy box',
    pf_buyBoxHint:      '— drag or type your minimums; blank = off',
    pf_daysNote:        'Days Listed counts from when we first tracked a listing — most sources hide the true list date.',
    pf_listingsFound:   'listings found',
    pf_loading:         'Loading…',

    // Property page — verdict banner
    pp_verdict_strong:      'Strong Buy',
    pp_verdict_strong_h:    'This property merits serious consideration by investor clients.',
    pp_verdict_worth:       'Worth Investigating',
    pp_verdict_worth_h:     'Good potential — thorough due diligence is recommended before committing.',
    pp_verdict_fair:        'Fairly Priced',
    pp_verdict_fair_h:      'Priced at market value — limited discount, limited upside at this price.',
    pp_verdict_not:         'Not Recommended',
    pp_verdict_not_h:       'Challenges outweigh the opportunity at the current asking price.',
    pp_m_capRate:           'Cap Rate',
    pp_m_belowMarket:       'Below Market',
    pp_m_cashFlow:          'Monthly Cash Flow',
    pp_m_grm:               'GRM',
    pp_m_noi:               'Annual NOI',
    pp_m_comparables:       'Comparables',
    pp_tapCard:             "Tap a card to see how it's calculated",
    // metric sub-badges
    pp_sub_aboveBench:  'Above benchmark',
    pp_sub_acceptable:  'Acceptable',
    pp_sub_belowFloor:  'Below floor',
    pp_sub_bigDiscount: 'Big discount',
    pp_sub_modestDiscount: 'Modest discount',
    pp_sub_marketPrice: 'Market price',
    pp_sub_aboveMarket: 'Above market',
    pp_sub_strongSurplus: 'Strong surplus',
    pp_sub_breakEven:   'Break-even',
    pp_sub_manageable:  'Manageable',
    pp_sub_topUp:       'Top-up needed',
    pp_sub_excellent:   'Excellent',
    pp_sub_elevated:    'Elevated',
    pp_sub_strongIncome:'Strong income',
    pp_sub_moderate:    'Moderate',
    pp_sub_thinMargin:  'Thin margin',
    pp_sub_negative:    'Negative',
    pp_sub_highConf:    'High confidence',
    pp_sub_lowConf:     'Low confidence',
    pp_sales:           'sales',
    // calc panel
    pp_noData:          'No data yet',
    pp_notEnoughComps:  'Not enough comparable sales',
    pp_noRentalData:    'No rental income data',
    pp_noComps:         'No comparable sales found',
    pp_howCalc:         "How it's calculated",
    pp_formula:         'Formula',
    pp_thisProperty:    'This property',
    pp_benchmarks:      'Benchmarks',
    pp_mean_capRate:    'Target: ≥6% strong buy · ≥4.5% acceptable · <4.5% below floor',
    pp_mean_below:      '≥10% = big discount · ≥3% = modest · negative = above market',
    pp_mean_cashFlow:   'Positive = self-sustaining · Negative = you top up monthly',
    pp_mean_grm:        '≤12x excellent · ≤15x acceptable · >15x expensive per rent dollar',
    pp_mean_noi:        "Net operating income — what the building earns before your loan payment",
    pp_mean_comps:      'More comps = higher confidence in the market value',
    // tabs + section headers + CTAs
    pp_tab_verdict:     'AI Verdict',
    pp_tab_comparables: 'Comparable Sales',
    pp_tab_zoning:      'Zoning',
    pp_multiSiteBanner: 'Same property listed on multiple sites',
    pp_h_roi:           'Annual Average ROI',
    pp_h_costBreakdown: 'Annual Cost Breakdown',
    pp_h_costSub:       'Where each rental dollar goes',
    pp_h_scoreBreakdown:'Score Breakdown',
    pp_h_scoreSum:      'Sum of factor points (before risk adjustments)',
    pp_h_signals:       'Investment Signals',
    pp_h_priceVsMarket: 'Price vs Comparable Market',
    pp_col_metric:      'Metric',
    pp_col_total:       'Total',
    pp_viewAnalysis:    'View Property Analysis',
    pp_generateAnalysis:'Generate Property Analysis',
    pp_roi_cashflow:    'Cashflow',
    pp_roi_appreciation:'Appreciation',
    pp_roi_capitalization:'Capitalization',
    pp_cost_mortgage:   'Mortgage',
    pp_cost_schoolTax:  'School Tax',
    pp_cost_maintenance:'Maintenance',
    pp_cost_netIncome:  'Net Income',
  },
  fr: {
    // Nav
    dashboard:   'Tableau de bord',
    properties:  'Propriétés',
    watching:    'Surveillance',
    settings:    'Paramètres',
    logout:      'Déconnexion',

    // Stats cards
    propertiesInArea:  'Propriétés dans la zone',
    newToday:          'Nouvelles aujourd\'hui',
    strongOpps:        'Opportunités fortes',
    worthInvest:       'À examiner',
    priceDrops:        'Baisses de prix',
    avgScore:          'Score moyen',

    // Score categories
    strongOpportunity:  'Excellente opportunité',
    worthInvestigating: 'À examiner',
    marketPrice:        'Prix du marché',
    notRecommended:     'Non recommandé',

    // Actions
    viewAnalysis:       'Voir l\'analyse',
    watchProperty:      'Surveiller',
    reanalyze:          'Ré-analyser',
    backToProperties:   'Retour aux propriétés',
    viewOnSource:       'Voir sur',

    // Filters
    filters:       'Filtres',
    sortBy:        'Trier par',
    allTypes:      'Tous les types',
    allCities:     'Toutes les villes',
    minScore:      'Score min.',
    anyScore:      'Tout',
    gridView:      'Grille',
    listView:      'Liste',
    noResults:     'Aucune propriété ne correspond à vos filtres.',
    noResultsHint: 'Essayez d\'élargir votre zone ou votre gamme de prix.',

    // Detail page tabs
    aiBrief:      'Analyse IA',
    financials:   'Finances',
    comparables:  'Comparables',
    priceHistory: 'Historique des prix',
    sources:      'Sources',

    // Financial labels
    askingPrice:    'Prix demandé',
    marketValue:    'Valeur marchande (ventes comparables)',
    valueGap:       'Économies vs marché',
    discount:       'Sous le prix du marché',
    capRate:        'Rendement annuel (taux de cap.)',
    cashFlow:       'Profit mensuel (flux de trésorerie)',
    cashOnCash:     'Retour sur mise de fonds',
    noi:            'Revenu net annuel',
    grm:            'Ratio prix/loyer',
    downPayment:    'Votre mise de fonds (20%)',
    welcomeTax:     'Droits de mutation',
    monthlyMortgage:'Paiement hypothécaire mensuel',
    rentalIncome:   'Revenu locatif mensuel',
    grossIncome:    'Revenu brut annuel',
    municipalTax:   'Taxes municipales annuelles',
    schoolTax:      'Taxes scolaires annuelles',
    condoFees:      'Frais de condo mensuels',
    pricePerSqft:   'Prix / pi²',
    compsFound:     'Ventes comparables trouvées',

    // Misc
    units:       'unités',
    sqft:        'pi²',
    built:       'Bâti',
    daysOnMarket:'jours sur le marché',
    newBadge:    'NOUVEAU',
    priceDrop:   'Baisse de prix',
    active:      'Actif',
    topOpps:     'Meilleures opportunités',
    newListings: 'Nouvelles annonces',
    coverage:    'Couverture',
    viewAll:     'Voir tout →',
    notFound:    'Propriété introuvable',
    notFoundHint:'Cette annonce a peut-être été retirée.',
    browseAll:   'Parcourir toutes les propriétés →',
    queued:      'En attente',
    lastAnalyzed:'Dernière analyse',
    firstSeen:   'Première vue',
    lastChecked: 'Dernière vérification',
    mlsNumber:   'MLS#',
    noPriceHistory:   'Aucun changement de prix enregistré.',
    noComparables:    'Aucun comparable trouvé pour cette propriété.',
    noSources:        'Aucune source active enregistrée.',
    noAiBrief:        'Analyse IA non encore générée.',
    noAiBriefLow:     'Score sous 40 — analyse non générée pour cette propriété.',
    runPipeline:      'Cliquez sur Ré-analyser pour soumettre cette propriété.',
    dealProfile:      'Profil de l\'investissement',
    confidencePill:   'confiance',
    analyzedUsing:    'analysés',
    within:           'dans un rayon de',
    medianPrice:      'Prix médian',
    meanPrice:        'Prix moyen',
    pricedAt:         'Affiché à',
    belowMarket:      'sous le marché',
    aboveMarket:      'au-dessus du marché',
    originalListing:  'Mise en vente initiale',
    totalReduction:   'Réduction totale',
    fromOriginal:     'du prix initial',
    settings_title:   'Paramètres',
    settings_subtitle:'Gérez votre compte et vos préférences de notification.',
    settings_saved:   'Préférences enregistrées',

    // Multi-site comparison
    multiSite:        'Multi-site',
    multiSiteFilter:  'Multi-site seulement',
    lowestPrice:      'Prix le plus bas',
    lowestPriceSite:  'Site le moins cher',
    savingsVsHighest: 'Économie vs le plus haut',
    onSites:          'sites',
    priceComparison:  'Comparaison de prix',
    lastUpdated:      'Mis à jour',

    // Nav (sidebar)
    nav_marketAlerts:    'Alertes du marché',
    nav_savedSearches:   'Recherches enregistrées',
    nav_reports:         'Rapports',
    nav_savedProperties: 'Propriétés enregistrées',
    nav_adminDashboard:  'Tableau admin',

    // Settings — header
    set_headerSubtitle: 'Vos préférences d\'investissement, enregistrées sur votre compte.',
    set_applyToSearch:  'Appliquer à la recherche',
    set_save:           'Enregistrer',
    set_saved:          'Enregistré',
    set_saving:         'Enregistrement…',

    // Settings — search location
    set_location_title: 'Zone de recherche',
    set_location_desc:  'Les villes où vous cherchez — choisissez-en autant que vous voulez.',
    set_targetCities:   'Villes ciblées',
    set_addAnother:     'Ajouter une autre…',
    set_cityPlaceholder:'ex. Montréal, Laval…',
    set_add:            'Ajouter',
    set_searchRadius:   'Rayon de recherche',

    // Settings — budget
    set_budget_title:   'Fourchette de prix',
    set_budget_desc:    'La tranche de prix dans laquelle vous investissez.',
    set_budget_under:   'Moins de 300 k$',
    set_budget_300500:  '300 k$ – 500 k$',
    set_budget_500750:  '500 k$ – 750 k$',
    set_budget_7501m:   '750 k$ – 1 M$',
    set_budget_over1m:  'Plus de 1 M$',
    set_budget_custom:  'Personnalisé',
    set_minPrice:       'Prix min.',
    set_maxPrice:       'Prix max.',
    set_any:            'Tout',

    // Settings — property types
    set_types_title:    'Types de propriété',
    set_types_desc:     'Choisissez tous les types qui vous intéressent.',
    type_duplex:        'Duplex',
    type_triplex:       'Triplex',
    type_quadruplex:    'Quadruplex',
    type_quintuplex:    'Quintuplex+',
    type_single_family: 'Unifamiliale',
    type_condo:         'Condo',
    units_2:            '2 logements',
    units_3:            '3 logements',
    units_4:            '4 logements',
    units_5plus:        '5+ logements',
    unit_house:         'maison',
    unit_apartment:     'appartement',

    // Settings — investment goal
    set_goal_title:     'Objectif d\'investissement',
    set_goal_desc:      'Choisissez la stratégie (ou les deux) que vous utilisez.',
    goal_hold_label:    'Achat & conservation',
    goal_hold_desc:     'Revenus locatifs mensuels des locataires',
    goal_hold_info:     'Vous conservez la propriété à long terme et la louez. L\'objectif est un flux de trésorerie mensuel stable et une appréciation à long terme. Avec cette stratégie, Votre Verdict s\'appuie sur le taux de capitalisation et le flux de trésorerie.',
    goal_flip_label:    'Revente (rénover & vendre)',
    goal_flip_desc:     'Acheter bas, rénover, revendre avec profit',
    goal_flip_info:     'Vous achetez sous le marché, rénovez et revendez pour un profit ponctuel — l\'écart entre votre coût d\'achat plus les rénovations et le prix de revente. Avec cette stratégie, Votre Verdict s\'appuie sur le rabais et les jours sur le marché (vendeurs motivés).',
    set_whatsThis:      'C\'est quoi ?',

    // Settings — alerts
    set_alerts_title:   'Déclencheurs d\'alerte',
    set_alerts_desc:    'Ce qui doit déclencher une notification.',
    set_newListings:    'Nouvelles annonces',
    set_newListings_sub:'Une propriété correspondant à vos critères apparaît',
    set_priceDrops:     'Baisses de prix',
    set_priceDrops_sub: 'Une annonce qui vous intéresse baisse de prix',
    set_minQuality:     'Qualité minimale',
    set_qualityAny:     'Tout',
    set_qualityGood:    'Bon',
    set_qualityTop:     'Élevé',
    set_qualityBest:    'Meilleur',

    // Settings — delivery
    set_delivery_title: 'Canaux de diffusion',
    set_delivery_desc:  'Comment vous joindre.',
    set_emailAlerts:    'Alertes courriel',
    set_sentTo:         'Envoyé à',
    set_sentToAccount:  'Envoyé au courriel de votre compte',
    set_smsWhatsapp:    'SMS et WhatsApp',
    set_comingSoon:     'Bientôt',
    set_phoneNumber:    'Numéro de téléphone',
    set_sms:            'SMS',
    set_sms_sub:        'Fonctionne sur tout téléphone',
    set_whatsapp:       'WhatsApp',
    set_whatsapp_sub:   'Messages enrichis avec photos',
    set_phoneNeeded:    'Entrez un numéro de téléphone valide pour activer SMS/WhatsApp.',

    // Settings — language
    set_language_title: 'Langue',
    set_language_desc:  'Langue de l\'interface.',

    // Settings — My Scoring Criteria
    set_scoring_title:  'Mes critères de notation',
    set_scoring_desc:   'Définissez votre buy box en chiffres réels. Les propriétés qui atteignent vos cibles sont affichées en premier et notées selon vos propres chiffres.',
    set_howThisWorks:   'Comment ça marche',
    set_yourBuyBox:     'Votre buy box',
    set_inNumbers:      '— en chiffres, pas en pourcentages',
    set_buyBoxHint:     'Définissez une cible avec le curseur ou en tapant un chiffre — laissez à « Désactivé » pour l\'ignorer. Les cibles filtrent la liste des propriétés et augmentent le score d\'une annonce d\'autant plus qu\'elle dépasse votre chiffre.',
    set_advanced:       'Avancé — ajustez le poids de chaque facteur dans le classement',
    set_reset:          'Réinitialiser',
    set_yourMix:        'Votre répartition',
    set_yourMix_desc:   'Chaque curseur est indépendant. Le beigne montre la part résultante de votre verdict.',
    set_topFactor:      'Facteur principal',
    set_off:            'Désactivé',
    preset_balanced:    'Équilibré',
    preset_cashflow:    'Flux de trésorerie',
    preset_buyhold:     'Achat & conservation',
    preset_value:       'Valeur / Revente',
    preset_custom:      'Personnalisé',
    factor_discount:    'Rabais sur prix',
    factor_cap_rate:    'Taux de cap.',
    factor_cash_flow:   'Flux de trésorerie',
    factor_grm:         'MRB',
    factor_confidence:  'Fiabilité',
    factor_dom_bonus:   'Jours affichés',
    factor_price_history:'Tendance de prix',
    factor_price_cut:   'Baisse de prix',
    fdesc_discount:     'À quel point le prix est sous les ventes comparables',
    fdesc_cap_rate:     'Rendement annuel — revenu net vs prix d\'achat',
    fdesc_cash_flow:    'Profit mensuel après hypothèque, taxes et dépenses',
    fdesc_grm:          'Prix par rapport au loyer brut (plus bas est mieux)',
    fdesc_confidence:   'À quel point les données comparables appuient les chiffres',
    fdesc_dom_bonus:    'Jours sur le marché — plus long = plus de levier vendeur',
    fdesc_price_cut:    'Baisse de prix depuis l\'affichage — signe d\'un vendeur motivé',
    // Scoring "how this works" modal
    help_intro:         'Votre Verdict classe chaque propriété selon vos chiffres plutôt que l\'opinion par défaut de l\'app. Ça fonctionne en trois étapes :',
    help_step1_title:   'Définissez vos cibles en chiffres réels',
    help_step2_title:   'Chaque annonce est notée selon vos chiffres',
    help_step3_title:   'Les facteurs se combinent en Votre Verdict',
    help_example:       'Exemple',
    help_note:          'Une protection : lorsque le loyer d\'une annonce est seulement estimé (non divulgué par le vendeur), les facteurs de revenu — taux de cap., flux de trésorerie, MRB — ne peuvent pas dépasser un score neutre, afin qu\'un loyer inventé ne gonfle pas un verdict.',
    help_step1_body:    'Utilisez les curseurs (ou tapez un chiffre) pour ce qui compte — p. ex. 200 $/mois de flux de trésorerie et 30+ jours sur le marché. Laissez le reste à Désactivé.',
    help_step2_body:    'Chaque facteur est noté de 0 à 100. Atteignez ou dépassez votre cible et il obtient 100 — plus une annonce dépasse votre chiffre, plus son score est élevé.',
    help_step3_body:    'Vos cibles (et tout ajustement d\'importance) se combinent en un seul score de 0 à 100, et toute la liste des propriétés est classée selon celui-ci — pas juste une page.',
    help_example_body:  'Une annonce à 250 $/mois (cible 200 $) affichée depuis 45 jours (cible 30) maximise les deux facteurs — elle se retrouve donc en haut de Votre Verdict.',

    // Dashboard
    dash_subtitle:      'Aperçu de l\'investissement immobilier au Québec',
    dash_newToday:      'Nouveau aujourd\'hui',
    dash_m_total:       'Total des propriétés',
    dash_m_total_sub:   'au Québec',
    dash_m_new:         'Nouvelles annonces',
    dash_m_new_sub:     'ajoutées aujourd\'hui',
    dash_m_great:       'Excellentes affaires',
    dash_m_great_sub:   'score 80+',
    dash_m_worth:       'À vérifier',
    dash_m_worth_sub:   'score 60–79',
    dash_m_drops:       'Baisses de prix',
    dash_m_drops_sub:   'depuis hier',
    dash_m_avg:         'Score moyen',
    dash_m_avg_sub:     'sur 100',
    dash_m_multi:       'Annonces multi-sites',
    dash_m_multi_sub:   'comparer les prix',
    dash_rankedYour:    'Classées selon vos propres critères',
    dash_bestNow:       'Meilleures opportunités d\'investissement en ce moment',
    dash_viewAll:       'Voir tout',
    dash_noScored:      'Aucune propriété notée pour l\'instant — lancez l\'analyse IA pour générer des scores.',
    dash_recentlyAdded: 'Récemment ajoutées à la base de données',
    dash_noNewToday:    'Aucune nouvelle annonce enregistrée aujourd\'hui.',
    dash_quickFilters:  'Filtres rapides',
    dash_qf_new24:      'Nouveau (24 h)',
    dash_qf_best:       'Meilleures affaires (80+)',
    dash_qf_drops:      'Baisses de prix',
    dash_qf_multi:      'Sur plusieurs sites',
    dash_qf_yield:      'Rendement le plus élevé',
    dash_topCities:     'Villes principales',
    dash_covered:       'couvertes',
    dash_moreCities:    'autres villes',
    time_justNow:       'À l\'instant',
    time_hAgo:          'h',
    time_dAgo:          'j',

    // Properties page
    ptype_duplex:       'Duplex (2 logements)',
    ptype_triplex:      'Triplex (3 logements)',
    ptype_quadruplex:   'Quadruplex (4 logements)',
    ptype_quintuplex:   'Quintuplex+ (5+ logements)',
    ptype_single:       'Maison unifamiliale',
    ptype_condo:        'Condo',
    pf_quality_any:     'Toute qualité',
    pf_quality_great:   'Excellentes affaires (80+)',
    pf_quality_worth:   'À vérifier (60+)',
    pf_quality_all:     'Tout afficher (40+)',
    pf_time_any:        'N\'importe quand',
    pf_time_24h:        'Dernières 24 h',
    pf_time_48h:        'Dernières 48 h',
    pf_time_7d:         'Derniers 7 jours',
    pf_time_30d:        'Derniers 30 jours',
    pf_sort_best:       'Meilleures affaires d\'abord',
    pf_sort_discount:   'Plus gros rabais d\'abord',
    pf_sort_priceasc:   'Prix le plus bas d\'abord',
    pf_sort_pricedesc:  'Prix le plus élevé d\'abord',
    pf_sort_newest:     'Plus récentes d\'abord',
    pf_sort_longest:    'Affichées le plus longtemps d\'abord',
    pf_chip_24h:        '24 h',
    pf_chip_48h:        '48 h',
    pf_chip_7d:         '7 jours',
    pf_chip_30d:        '30 jours',
    pf_chip_best:       'Meilleures affaires',
    pf_chip_discount:   'Plus gros rabais',
    pf_chip_lowest:     'Prix le plus bas',
    pf_chip_highest:    'Prix le plus élevé',
    pf_searchPlaceholder:'Rechercher une adresse ou une ville…',
    pf_mlsPlaceholder:  'Numéro MLS…',
    pf_egMin:           'ex. 300000',
    pf_egMax:           'ex. 1000000',
    pf_of:              'sur',
    pf_listingsMatch:   'annonces correspondent à vos critères',
    pf_rankAI:          'IA',
    pf_rankMine:        'Mes critères',
    pf_clear:           'Effacer',
    pf_clearAll:        'Tout effacer',
    pf_propertyType:    'Type de propriété',
    pf_minQuality:      'Qualité minimale',
    pf_listedWithin:    'Affichées depuis',
    pf_city:            'Ville',
    pf_minPrice:        'Prix min. ($)',
    pf_maxPrice:        'Prix max. ($)',
    pf_multiOnly:       'Affichées sur plusieurs sites',
    pf_sizeData:        'Données de superficie',
    pf_hasSqft:         'Avec superficie seulement',
    pf_floodRisk:       'Risque d\'inondation',
    pf_floodOnly:       'Zone inondable seulement',
    pf_noResults:       'Aucune propriété trouvée',
    pf_noResultsHint:   'Essayez d\'ajuster vos filtres ou d\'élargir la zone de recherche.',
    pf_clearAllFilters: 'Effacer tous les filtres',
    pf_buyBoxTitle:     'Votre buy box',
    pf_buyBoxHint:      '— glissez ou tapez vos minimums; vide = désactivé',
    pf_daysNote:        'Les jours affichés comptent à partir de notre premier suivi — la plupart des sources masquent la vraie date d\'affichage.',
    pf_listingsFound:   'annonces trouvées',
    pf_loading:         'Chargement…',

    // Property page — verdict banner
    pp_verdict_strong:      'Achat fort',
    pp_verdict_strong_h:    'Cette propriété mérite une considération sérieuse de vos clients investisseurs.',
    pp_verdict_worth:       'À examiner',
    pp_verdict_worth_h:     'Bon potentiel — une vérification diligente approfondie est recommandée avant de vous engager.',
    pp_verdict_fair:        'Prix juste',
    pp_verdict_fair_h:      'Au prix du marché — rabais limité, potentiel limité à ce prix.',
    pp_verdict_not:         'Non recommandé',
    pp_verdict_not_h:       'Les défis l\'emportent sur l\'occasion au prix demandé actuel.',
    pp_m_capRate:           'Taux de cap.',
    pp_m_belowMarket:       'Sous le marché',
    pp_m_cashFlow:          'Flux de trésorerie mensuel',
    pp_m_grm:               'MRB',
    pp_m_noi:               'RNE annuel',
    pp_m_comparables:       'Comparables',
    pp_tapCard:             'Touchez une carte pour voir le calcul',
    // metric sub-badges
    pp_sub_aboveBench:  'Au-dessus du seuil',
    pp_sub_acceptable:  'Acceptable',
    pp_sub_belowFloor:  'Sous le plancher',
    pp_sub_bigDiscount: 'Gros rabais',
    pp_sub_modestDiscount: 'Rabais modeste',
    pp_sub_marketPrice: 'Prix du marché',
    pp_sub_aboveMarket: 'Au-dessus du marché',
    pp_sub_strongSurplus: 'Fort surplus',
    pp_sub_breakEven:   'Seuil de rentabilité',
    pp_sub_manageable:  'Gérable',
    pp_sub_topUp:       'Appoint requis',
    pp_sub_excellent:   'Excellent',
    pp_sub_elevated:    'Élevé',
    pp_sub_strongIncome:'Fort revenu',
    pp_sub_moderate:    'Modéré',
    pp_sub_thinMargin:  'Marge mince',
    pp_sub_negative:    'Négatif',
    pp_sub_highConf:    'Haute fiabilité',
    pp_sub_lowConf:     'Faible fiabilité',
    pp_sales:           'ventes',
    // calc panel
    pp_noData:          'Pas encore de données',
    pp_notEnoughComps:  'Pas assez de ventes comparables',
    pp_noRentalData:    'Aucune donnée de revenu locatif',
    pp_noComps:         'Aucune vente comparable trouvée',
    pp_howCalc:         'Comment c\'est calculé',
    pp_formula:         'Formule',
    pp_thisProperty:    'Cette propriété',
    pp_benchmarks:      'Repères',
    pp_mean_capRate:    'Cible : ≥6 % achat fort · ≥4,5 % acceptable · <4,5 % sous le plancher',
    pp_mean_below:      '≥10 % = gros rabais · ≥3 % = modeste · négatif = au-dessus du marché',
    pp_mean_cashFlow:   'Positif = autofinancé · Négatif = vous comblez chaque mois',
    pp_mean_grm:        '≤12x excellent · ≤15x acceptable · >15x cher par dollar de loyer',
    pp_mean_noi:        'Revenu net d\'exploitation — ce que l\'immeuble génère avant votre paiement de prêt',
    pp_mean_comps:      'Plus de comparables = plus de confiance dans la valeur marchande',
    // tabs + section headers + CTAs
    pp_tab_verdict:     'Verdict IA',
    pp_tab_comparables: 'Ventes comparables',
    pp_tab_zoning:      'Zonage',
    pp_multiSiteBanner: 'Même propriété affichée sur plusieurs sites',
    pp_h_roi:           'RCI moyen annuel',
    pp_h_costBreakdown: 'Répartition des coûts annuels',
    pp_h_costSub:       'Où va chaque dollar de loyer',
    pp_h_scoreBreakdown:'Détail du score',
    pp_h_scoreSum:      'Somme des points des facteurs (avant ajustements de risque)',
    pp_h_signals:       'Signaux d\'investissement',
    pp_h_priceVsMarket: 'Prix vs marché comparable',
    pp_col_metric:      'Métrique',
    pp_col_total:       'Total',
    pp_viewAnalysis:    'Voir l\'analyse de la propriété',
    pp_generateAnalysis:'Générer l\'analyse de la propriété',
    pp_roi_cashflow:    'Flux de trésorerie',
    pp_roi_appreciation:'Appréciation',
    pp_roi_capitalization:'Capitalisation',
    pp_cost_mortgage:   'Hypothèque',
    pp_cost_schoolTax:  'Taxe scolaire',
    pp_cost_maintenance:'Entretien',
    pp_cost_netIncome:  'Revenu net',
  },
} as const

type LangKey = keyof typeof TRANSLATIONS['en']

export type { LangKey }

interface LanguageContextType {
  lang: 'en' | 'fr'
  setLang: (l: 'en' | 'fr') => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | null>(null)

const LANG_KEY = 'quartis.lang'

function initialLang(): 'en' | 'fr' {
  try {
    const saved = localStorage.getItem(LANG_KEY)
    if (saved === 'en' || saved === 'fr') return saved
  } catch { /* ignore */ }
  return 'en'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<'en' | 'fr'>(initialLang)

  // Persist the choice so it survives reloads (previously reset to English).
  const setLang = (l: 'en' | 'fr') => {
    setLangState(l)
    try { localStorage.setItem(LANG_KEY, l) } catch { /* ignore */ }
  }

  const t = (key: string): string => (TRANSLATIONS[lang] as Record<string, string>)[key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider')
  return ctx
}
