import { createContext, useContext, useState, type ReactNode } from 'react'

export const TRANSLATIONS = {
  en: {
    // Nav
    dashboard:   'Dashboard',
    properties:  'Properties',
    watching:    'Watching',
    settings:    'Settings',
    logout:      'Logout',

    // Stats cards
    propertiesInArea:  'Properties in Area',
    newToday:          'New Today',
    strongOpps:        'Strong Opportunities',
    worthInvest:       'Worth Investigating',
    priceDrops:        'Price Drops Today',
    avgScore:          'Avg Score',

    // Score categories
    strongOpportunity:  'Strong Opportunity',
    worthInvestigating: 'Worth Investigating',
    marketPrice:        'Market Price',
    notRecommended:     'Not Recommended',

    // Actions
    viewAnalysis:       'View Analysis',
    watchProperty:      'Watch',
    reanalyze:          'Re-analyze',
    backToProperties:   'Back to properties',
    viewOnSource:       'View on',

    // Filters
    filters:       'Filters',
    sortBy:        'Sort by',
    allTypes:      'All types',
    allCities:     'All cities',
    minScore:      'Min score',
    anyScore:      'Any',
    gridView:      'Grid',
    listView:      'List',
    noResults:     'No properties match your filters.',
    noResultsHint: 'Try expanding your price range or area.',

    // Detail page tabs
    aiBrief:      'AI Brief',
    financials:   'Financials',
    comparables:  'Comparables',
    priceHistory: 'Price History',
    sources:      'Sources',

    // Financial labels
    askingPrice:    'Asking Price',
    marketValue:    'Market Value (comparable sales)',
    valueGap:       'Your savings vs market',
    discount:       'Below market price',
    capRate:        'Yearly return (cap rate)',
    cashFlow:       'Monthly profit (cash flow)',
    cashOnCash:     'Return on cash invested',
    noi:            'Net annual income',
    grm:            'Price/rent ratio (GRM)',
    downPayment:    'Your down payment (20%)',
    welcomeTax:     'Welcome tax (droits de mutation)',
    monthlyMortgage:'Monthly mortgage payment',
    rentalIncome:   'Monthly rental income',
    grossIncome:    'Annual gross income',
    municipalTax:   'Municipal property taxes',
    schoolTax:      'School taxes (annual)',
    condoFees:      'Monthly condo fees',
    pricePerSqft:   'Price per sqft',
    compsFound:     'Comparable sales found',

    // Misc
    units:       'units',
    sqft:        'sqft',
    built:       'Built',
    daysOnMarket:'days on market',
    newBadge:    'NEW',
    priceDrop:   'Price Drop',
    active:      'Active',
    topOpps:     'Top Opportunities',
    newListings: 'New Listings',
    coverage:    'Coverage',
    viewAll:     'View all →',
    notFound:    'Property not found',
    notFoundHint:'This listing may have been delisted or removed.',
    browseAll:   'Browse all properties →',
    queued:      'Queued',
    lastAnalyzed:'Last analyzed',
    firstSeen:   'First seen',
    lastChecked: 'Last checked',
    mlsNumber:   'MLS#',
    noPriceHistory:   'No price changes recorded.',
    noComparables:    'No comparables found for this property.',
    noSources:        'No active sources recorded.',
    noAiBrief:        'AI brief not yet generated.',
    noAiBriefLow:     'Score below 40 — brief not generated for this property.',
    runPipeline:      'Click Re-analyze to queue this property.',
    dealProfile:      'Deal Profile',
    confidencePill:   'confidence',
    analyzedUsing:    'analyzed',
    within:           'within',
    medianPrice:      'Median Price',
    meanPrice:        'Mean Price',
    pricedAt:         'Priced',
    belowMarket:      'below market',
    aboveMarket:      'above market',
    originalListing:  'Originally listed',
    totalReduction:   'Total reduction',
    fromOriginal:     'from original',
    settings_title:   'Settings',
    settings_subtitle:'Manage your account and notification preferences.',
    settings_saved:   'Preferences saved',

    // Multi-site comparison
    multiSite:        'Multi-site',
    multiSiteFilter:  'Multi-site only',
    lowestPrice:      'Lowest price',
    lowestPriceSite:  'Lowest price site',
    savingsVsHighest: 'Save vs highest',
    onSites:          'sites',
    priceComparison:  'Price Comparison',
    lastUpdated:      'Updated',

    // Nav (sidebar)
    nav_marketAlerts:    'Market Alerts',
    nav_savedSearches:   'Saved Searches',
    nav_reports:         'Reports',
    nav_savedProperties: 'Saved Properties',
    nav_adminDashboard:  'Admin Dashboard',

    // Settings — header
    set_headerSubtitle: 'Your investment preferences, saved to your account.',
    set_applyToSearch:  'Apply to search',
    set_save:           'Save preferences',
    set_saved:          'Saved',
    set_saving:         'Saving…',

    // Settings — search location
    set_location_title: 'Search location',
    set_location_desc:  "The cities you're hunting in — pick as many as you like.",
    set_targetCities:   'Target cities',
    set_addAnother:     'Add another…',
    set_cityPlaceholder:'e.g. Montréal, Laval…',
    set_add:            'Add',
    set_searchRadius:   'Search radius',

    // Settings — budget
    set_budget_title:   'Budget range',
    set_budget_desc:    'The price band you invest in.',
    set_budget_under:   'Under $300K',
    set_budget_300500:  '$300K – $500K',
    set_budget_500750:  '$500K – $750K',
    set_budget_7501m:   '$750K – $1M',
    set_budget_over1m:  'Over $1M',
    set_budget_custom:  'Custom',
    set_minPrice:       'Min price',
    set_maxPrice:       'Max price',
    set_any:            'Any',

    // Settings — property types
    set_types_title:    'Property types',
    set_types_desc:     "Pick every type you'd consider.",
    type_duplex:        'Duplex',
    type_triplex:       'Triplex',
    type_quadruplex:    'Quadruplex',
    type_quintuplex:    'Quintuplex+',
    type_single_family: 'Single Family',
    type_condo:         'Condo',
    units_2:            '2 units',
    units_3:            '3 units',
    units_4:            '4 units',
    units_5plus:        '5+ units',
    unit_house:         'house',
    unit_apartment:     'apartment',

    // Settings — investment goal
    set_goal_title:     'Investment goal',
    set_goal_desc:      'Pick the strategy (or both) you invest with.',
    goal_hold_label:    'Buy & Hold',
    goal_hold_desc:     'Monthly rental income from tenants',
    goal_hold_info:     'You keep the property long-term and rent it out. The goal is steady monthly cash flow plus long-term appreciation. With this strategy Your Verdict leans on cap rate and cash flow.',
    goal_flip_label:    'Flip (Fix & Sell)',
    goal_flip_desc:     'Buy cheap, renovate, sell for profit',
    goal_flip_info:     'You buy below market, renovate, and resell for a one-time profit — the spread between what you paid plus reno costs and the resale price. With this strategy Your Verdict leans on price discount and days-on-market (motivated sellers).',
    set_whatsThis:      "What's this?",
    set_useStarterNumbers: 'Use starter numbers',

    // Settings — alerts
    set_alerts_title:   'Alert triggers',
    set_alerts_desc:    'What should trigger a notification.',
    set_newListings:    'New listings',
    set_newListings_sub:'A property matching your criteria appears',
    set_priceDrops:     'Price drops',
    set_priceDrops_sub: "A listing you'd want drops in price",
    set_minQuality:     'Min deal quality',
    set_qualityAny:     'Any',
    set_qualityGood:    'Good',
    set_qualityTop:     'Top',
    set_qualityBest:    'Best',

    // Settings — delivery
    set_delivery_title: 'Delivery channels',
    set_delivery_desc:  'How we reach you.',
    set_emailAlerts:    'Email alerts',
    set_sentTo:         'Sent to',
    set_sentToAccount:  'Sent to your account email',
    set_smsWhatsapp:    'SMS & WhatsApp',
    set_comingSoon:     'Coming soon',
    set_phoneNumber:    'Phone number',
    set_sms:            'SMS',
    set_sms_sub:        'Works on any phone',
    set_whatsapp:       'WhatsApp',
    set_whatsapp_sub:   'Rich messages with photos',
    set_phoneNeeded:    'Enter a valid phone number to enable SMS/WhatsApp.',

    // Settings — language
    set_language_title: 'Language',
    set_language_desc:  'Interface language.',

    // Settings — My Scoring Criteria
    set_scoring_title:  'My Scoring Criteria',
    set_scoring_desc:   'Set your buy box in real numbers. Properties that meet your targets are shown first and scored against your own numbers.',
    set_howThisWorks:   'How this works',
    set_yourBuyBox:     'Your buy box',
    set_inNumbers:      '— in numbers, not percentages',
    set_buyBoxHint:     'Set a target with the slider or by typing a number — leave it at Off to ignore it. A listing that meets your number scores a full 100 on that factor in Your Verdict, and the closer it gets the more points it earns. Open “How is this calculated?” on any property to see the points add up.',
    set_advanced:       'Advanced — fine-tune how factors are weighted when ranking',
    set_reset:          'Reset',
    set_yourMix:        'Your mix',
    set_yourMix_desc:   'Each slider is independent. The donut shows the resulting share of your verdict.',
    set_topFactor:      'Top factor',
    set_off:            'Off',
    preset_balanced:    'Balanced',
    preset_cashflow:    'Cash-flow',
    preset_buyhold:     'Buy & Hold',
    preset_value:       'Value / Flip',
    preset_custom:      'Custom',
    factor_discount:    'Price Discount',
    factor_cap_rate:    'Cap Rate',
    factor_cash_flow:   'Cash Flow',
    factor_grm:         'GRM',
    factor_confidence:  'Confidence',
    factor_dom_bonus:   'Days Listed',
    factor_price_history:'Price Trend',
    factor_price_cut:   'Price Cut',
    fdesc_discount:     'How far below comparable sales it is priced',
    fdesc_cap_rate:     'Annual return — net income vs. purchase price',
    fdesc_cash_flow:    'Monthly profit after mortgage, taxes & expenses',
    fdesc_grm:          'Price relative to gross rent (lower is better)',
    fdesc_confidence:   'How much comparable data backs the numbers',
    fdesc_dom_bonus:    'Days on market — longer means more seller leverage',
    fdesc_price_cut:    'Price cut since listing — a motivated-seller signal',
    // Scoring "how this works" modal
    help_intro:         'Your Verdict ranks every property by your numbers instead of the app\'s default opinion. It works in three steps:',
    help_step1_title:   'Set your targets in real numbers',
    help_step2_title:   'Every listing is scored against your numbers',
    help_step3_title:   'The factors combine into Your Verdict',
    help_example:       'Example',
    help_note:          "One guardrail: when a listing's rent is only estimated (not disclosed by the seller), the income factors — cap rate, cash flow, GRM — can't score above neutral, so made-up rent can't inflate a verdict.",
    help_step1_body:    'Use the sliders (or type a number) for what matters — e.g. $200/mo cash flow and 30+ days on market. Leave the rest Off.',
    help_step2_body:    'Each factor scores 0–100. Meet or beat your target and it scores 100 — the more a listing beats your number, the higher it scores.',
    help_step3_body:    'Your targets (and any importance tweaks) blend into one 0–100 score, and the whole Properties list is ranked by it — not just one page.',
    help_example_body:  'A listing at $250/mo (target $200) that has been up 45 days (target 30) maxes out both factors — so it lands near the top of Your Verdict.',

    // Dashboard
    dash_subtitle:      'Quebec real estate investment overview',
    theme_light:        'Light mode',
    theme_dark:         'Dark mode',
    dash_greetMorning:  'Good morning',
    dash_greetMorning2: 'Rise and shine',
    dash_greetAfternoon:'Good afternoon',
    dash_greetAfternoon2:'Hope your day’s going well',
    dash_greetEvening:  'Good evening',
    dash_greetEvening2: 'Winding down',
    dash_greetNight:    'Working late',
    dash_greetNight2:   'Burning the midnight oil',
    dash_sub_new:       'new today',
    dash_sub_strong:    'strong buys',
    dash_newToday:      'New today',
    dash_m_total:       'Total properties',
    dash_m_total_sub:   'across Quebec',
    dash_m_new:         'New listings',
    dash_m_new_sub:     'added today',
    dash_m_great:       'Great deals',
    dash_m_great_sub:   'score 80+',
    dash_m_worth:       'Worth checking',
    dash_m_worth_sub:   'score 60–79',
    dash_m_drops:       'Price drops',
    dash_m_drops_sub:   'since yesterday',
    dash_m_avg:         'Avg deal score',
    dash_m_avg_sub:     'out of 100',
    dash_m_multi:       'Multi-site listings',
    dash_m_multi_sub:   'compare prices',
    dash_rankedYour:    'Ranked by your own scoring criteria',
    dash_bestNow:       'Best investment opportunities right now',
    dash_viewAll:       'View all',
    dash_noScored:      'No scored properties yet — run the AI pipeline to generate scores.',
    dash_recentlyAdded: 'Recently added to database',
    dash_noNewToday:    'No new listings recorded today.',
    analyze_title:          'Analyze any property',
    analyze_placeholder:    'Paste a Centris link  or  type a full address…',
    analyze_cta:            'Analyze',
    analyze_hint:           'We fetch it live and run the full analysis in about a minute.',
    analyze_linkDetected:   'Link',
    analyze_addressDetected:'Address',
    analyze_inYourDb:       'Already in your database',
    analyze_notListed:      'Not listed here? We’ll fetch it live.',
    analyze_recent:         'Your recent lookups',
    analyze_subtitle:       'Paste a Centris link or type an address — we fetch it live and score it on your numbers.',
    analyze_placeholder_address: 'Type a full address…  e.g. 32 Rue des Érables, Saint-Sixte',
    analyze_placeholder_link:    'Paste a Centris listing link…',
    analyze_starting:       'Starting…',
    analyze_try:            'Try:',
    analyze_modal_title:    'Analyzing property…',
    analyze_step_retrieving:'Retrieving the listing',
    analyze_step_analyzing: 'Analyzing the property',
    analyze_step_ready:     'Almost ready',
    analyze_tip1:           'Fetching live data straight from Centris.',
    analyze_tip2:           'Scoring it on your own investment criteria.',
    analyze_tip3:           'Crunching taxes, income and cash flow.',
    analyze_err_needsUrl_title:   'Couldn’t find that address',
    analyze_err_needsUrl_body:    'We couldn’t match that address to an active listing. Paste the Centris link instead.',
    analyze_err_unavailable_title:'Scraping temporarily unavailable',
    analyze_err_unavailable_body: 'We couldn’t reach the listing right now — a temporary scraping issue, not a problem with the property. Please try again shortly.',
    analyze_err_notFound_title:   'Nothing to analyze',
    analyze_err_failed_title:     'Analysis failed',
    analyze_err_failed_body:      'We couldn’t retrieve that listing. Check the link and try again.',
    analyze_err_duproprio:        'DuProprio isn’t supported yet — try a Centris link.',
    analyze_err_noScrapfly:       'Scraping isn’t configured on this server.',
    analyze_pasteLink:      'Paste a listing link',
    analyze_close:          'Close',
    analyze_freeUsed:       'free analyses used',
    analyze_limitTitle:     'You’ve used all 10 free analyses',
    analyze_limitBody:      'Upgrade to Pro for unlimited live property analysis across Québec.',
    analyze_proSoon:        'Pro plan — coming soon',
    recent_title:       'My recent analyses',
    recent_subtitle:    'Properties you analyzed, readable at a glance.',
    recent_capRate:     'Cap rate',
    recent_cashflow:    'Cashflow',
    recent_perMo:       '/mo',
    recent_viewReport:  'View full report',
    recent_justNow:     'just now',
    recent_minAgo:      'min ago',
    recent_hrAgo:       'h ago',
    recent_dayAgo:      'd ago',
    recent_analyzedOn:  'Analyzed',
    recent_price:       'Price',
    recent_score:       'Score',
    recent_positive:    'Positive',
    recent_negative:    'Negative',
    recent_delete:      'Remove',
    pp_loading_title:   'Building your analysis…',
    pp_loading_sub:     'Crunching the numbers and rendering your full report.',
    pp_step_fetch:      'Listing',
    pp_step_score:      'Scoring',
    pp_step_render:     'Report',
    dash_quickFilters:  'Quick Filters',
    dash_qf_new24:      'New last 24h',
    dash_qf_best:       'Best deals (80+)',
    dash_qf_drops:      'Price drops',
    dash_qf_multi:      'On multiple sites',
    dash_qf_yield:      'Highest yield',
    dash_topCities:     'Top Cities',
    dash_covered:       'covered',
    dash_moreCities:    'more cities',
    time_justNow:       'Just now',
    time_hAgo:          'h ago',
    time_dAgo:          'd ago',

    // Properties page
    ptype_duplex:       'Duplex (2 units)',
    ptype_triplex:      'Triplex (3 units)',
    ptype_quadruplex:   'Quadruplex (4 units)',
    ptype_quintuplex:   'Quintuplex+ (5+ units)',
    ptype_single:       'Single Family Home',
    ptype_condo:        'Condo',
    pf_category:        'Category',
    category_residential: 'Residential',
    category_commercial:  'Commercial',
    category_land:         'Land',
    pf_quality_any:     'Any quality',
    pf_quality_great:   'Great deals only (80+)',
    pf_quality_worth:   'Worth checking (60+)',
    pf_quality_all:     'Show everything (40+)',
    pf_time_any:        'Any time',
    pf_time_24h:        'Last 24 hours',
    pf_time_48h:        'Last 48 hours',
    pf_time_7d:         'Last 7 days',
    pf_time_30d:        'Last 30 days',
    pf_sort_best:       'Best deals first',
    pf_sort_discount:   'Biggest discount first',
    pf_sort_priceasc:   'Lowest price first',
    pf_sort_pricedesc:  'Highest price first',
    pf_sort_newest:     'Newest listings first',
    pf_sort_longest:    'Longest listed first',
    pf_chip_24h:        'Last 24h',
    pf_chip_48h:        'Last 48h',
    pf_chip_7d:         'Last 7 days',
    pf_chip_30d:        'Last 30 days',
    pf_chip_best:       'Best deals',
    pf_chip_discount:   'Biggest discount',
    pf_chip_lowest:     'Lowest price',
    pf_chip_highest:    'Highest price',
    pf_searchPlaceholder:'Search address or city…',
    pf_mlsPlaceholder:  'MLS number…',
    pf_egMin:           'e.g. 300000',
    pf_egMax:           'e.g. 1000000',
    pf_of:              'of',
    pf_listingsMatch:   'listings match your criteria',
    pf_rankAI:          'AI',
    pf_rankMine:        'My Metrics',
    pf_clear:           'Clear',
    pf_clearAll:        'Clear all',
    pf_propertyType:    'Property Type',
    pf_minQuality:      'Minimum quality',
    pf_listedWithin:    'Listed within',
    pf_city:            'City',
    pf_minPrice:        'Min price ($)',
    pf_maxPrice:        'Max price ($)',
    pf_multiOnly:       'Listed on multiple sites',
    pf_sizeData:        'Size data',
    pf_hasSqft:         'Has sqft only',
    pf_floodRisk:       'Flood risk',
    pf_floodOnly:       'Flagged flood zone only',
    pf_noResults:       'No properties found',
    pf_noResultsHint:   'Try adjusting your filters or expanding the search area.',
    pf_noResultsHardHint: 'Your buy box only ranks listings — this is empty because of your budget, property type, or city. Nothing on the market matches that combination. Try loosening one:',
    pf_dropBudget:      'Remove budget limit',
    pf_dropType:        'Any property type',
    pf_clearAllFilters: 'Clear all filters',
    pf_buyBoxTitle:     'Your buy box',
    pf_buyBoxHint:      '— drag or type your minimums; blank = off',
    pf_daysNote:        'Days Listed counts from when we first tracked a listing — most sources hide the true list date.',
    pf_listingsFound:   'listings found',
    pf_loading:         'Loading…',

    // Property page — verdict banner
    pp_verdict_strong:      'Strong Buy',
    pp_verdict_strong_h:    'This property merits serious consideration by investor clients.',
    pp_verdict_worth:       'Worth Investigating',
    pp_verdict_worth_h:     'Good potential — thorough due diligence is recommended before committing.',
    pp_verdict_fair:        'Fairly Priced',
    pp_verdict_fair_h:      'Priced at market value — limited discount, limited upside at this price.',
    pp_verdict_not:         'Not Recommended',
    pp_verdict_not_h:       'Challenges outweigh the opportunity at the current asking price.',
    pp_m_capRate:           'Cap Rate',
    pp_m_belowMarket:       'Below Market',
    pp_m_cashFlow:          'Monthly Cash Flow',
    pp_m_grm:               'GRM',
    pp_m_noi:               'Annual NOI',
    pp_m_comparables:       'Comparables',
    pp_tapCard:             "Tap a card to see how it's calculated",
    // metric sub-badges
    pp_sub_aboveBench:  'Above benchmark',
    pp_sub_acceptable:  'Acceptable',
    pp_sub_belowFloor:  'Below floor',
    pp_sub_bigDiscount: 'Big discount',
    pp_sub_modestDiscount: 'Modest discount',
    pp_sub_marketPrice: 'Market price',
    pp_sub_aboveMarket: 'Above market',
    pp_sub_strongSurplus: 'Strong surplus',
    pp_sub_breakEven:   'Break-even',
    pp_sub_manageable:  'Manageable',
    pp_sub_topUp:       'Top-up needed',
    pp_sub_excellent:   'Excellent',
    pp_sub_elevated:    'Elevated',
    pp_sub_strongIncome:'Strong income',
    pp_sub_moderate:    'Moderate',
    pp_sub_thinMargin:  'Thin margin',
    pp_sub_negative:    'Negative',
    pp_sub_highConf:    'High confidence',
    pp_sub_lowConf:     'Low confidence',
    pp_sales:           'sales',
    // calc panel
    pp_noData:          'No data yet',
    pp_notEnoughComps:  'Not enough comparable sales',
    pp_noRentalData:    'No rental income data',
    pp_noComps:         'No comparable sales found',
    pp_howCalc:         "How it's calculated",
    pp_formula:         'Formula',
    pp_thisProperty:    'This property',
    pp_benchmarks:      'Benchmarks',
    pp_mean_capRate:    'Target: ≥6% strong buy · ≥4.5% acceptable · <4.5% below floor',
    pp_mean_below:      '≥10% = big discount · ≥3% = modest · negative = above market',
    pp_mean_cashFlow:   'Positive = self-sustaining · Negative = you top up monthly',
    pp_mean_grm:        '≤12x excellent · ≤15x acceptable · >15x expensive per rent dollar',
    pp_mean_noi:        "Net operating income — what the building earns before your loan payment",
    pp_mean_comps:      'More comps = higher confidence in the market value',
    // tabs + section headers + CTAs
    pp_tab_verdict:     'AI Verdict',
    pp_tab_comparables: 'Comparable Sales',
    pp_tab_zoning:      'Zoning',
    // Zoning tab — plain-language headline, honesty badge, verification links, empty states
    pp_zh_plan_upside:   'Development signal — the city plans for more homes here than are built today. This is a city planning estimate, not a per-lot permit; confirm the exact limit with the borough before counting on it.',
    pp_zh_plan_none:     'Already built to about the density the city plan targets. Any further upside would come from the borough’s own zoning bylaw, not the citywide plan.',
    pp_zh_lot_envelope:  'This lot may support more units than are built today — an estimate from the zoning envelope (lot size × coverage × height). Treat it as capacity to confirm with the city, not a guaranteed permit.',
    pp_zh_lot_permit:    'The zoning bylaw here permits more units than are built today. Verify the grid with the city, then see the rebuild economics below.',
    pp_zh_lot_none:      'Already built at or near what the zoning allows — limited added-unit upside. The financials and rebuild math below still apply.',
    pp_zh_unknown:       'We couldn’t estimate added-unit potential for this lot yet — its lot size or the zone’s rules aren’t on record. The financials and checks below still apply.',
    pp_zh_today:         'today',
    pp_zh_potential:     'potential',
    pp_zoning_badge_plan:'City plan estimate',
    pp_zoning_verify_montreal:'Look up this address on Montréal’s zoning map',
    pp_zoning_verify_laval:'Open the Laval zoning bylaw (PDF)',
    pp_zoning_verify_qc: 'Open Québec City’s interactive zoning map',
    pp_zoning_verify_generic:'Verify on the city’s official site',
    pp_zoning_source_generic:'Verify this lot on the city’s official map',
    pp_zoning_empty_title_nc:'No zoning data available yet',
    pp_zoning_empty_title_um:'Couldn’t locate this lot',
    pp_zoning_empty_nc_b:' isn’t in our zoning coverage yet — we currently cover Montréal and Laval, expanding city by city. Everything else on this property still works.',
    pp_zoning_empty_um_a:'We couldn’t pinpoint this lot in ',
    pp_zoning_empty_um_b:'’s zoning layer — its coordinates may fall just outside a mapped zone. Everything else on this property — score, financials and alerts — still works.',
    // Zoning tab — full translation (measurements, explainer, rebuild calculator, records, constraints)
    zt_tab_title: 'Zoning & Development Potential',
    zt_badge_verified: 'Verified', zt_badge_partial: 'Partial data', zt_badge_basic: 'Basic zone info',
    zt_lotSqft: 'lot sqft', zt_official: 'official', zt_buildingSqft: 'building sqft', zt_landUse: 'land use', zt_zoneCode: 'zone code',
    zt_tm_T1: 'Natural — protected/low-impact areas', zt_tm_T2: 'Agricultural — farming perimeter',
    zt_tm_T3: 'Suburban — mostly single-family, low density', zt_tm_T4: 'Urban — gentle densification, up to ~2-3 storeys',
    zt_tm_T5: 'Urban compact — medium-high density, up to 25 storeys', zt_tm_T6: 'Urban centrality — highest density zone',
    zt_tm_CI: 'Institutional', zt_tm_ZC: 'Commercial zone', zt_tm_ZE: 'Ecological zone', zt_tm_ZH: 'Housing zone',
    zt_tm_ZI: 'Industrial zone', zt_tm_ZM: 'Mixed zone', zt_tm_ZP: 'Park zone', zt_tm_SZD: 'Special development zone',
    zt_tier_1log_l: 'Single dwelling', zt_tier_1log_d: 'One home on the lot — no added-unit potential here unless the zone also permits a higher tier.',
    zt_tier_2or3_l: '2–3 dwellings', zt_tier_2or3_d: 'A duplex or triplex: up to three separate units in one building.',
    zt_tier_4plus_l: '4+ dwellings', zt_tier_4plus_d: 'A small apartment building — four units or more. The exact ceiling comes from the lot size, coverage and height limits.',
    zt_tier_h2_l: 'Duplex (H2)', zt_tier_h2_d: 'A two-dwelling residential building.',
    zt_tier_h2c_l: 'Multi-unit (H2)', zt_tier_h2c_d: 'A multi-dwelling residential building type.',
    zt_tier_h3_l: 'Triplex (H3)', zt_tier_h3_d: 'A three-dwelling building type recognised by the bylaw.',
    zt_tier_h4_l: '4+ unit building (H4)', zt_tier_h4_d: 'A residential building of four or more dwellings.',
    zt_struct_iso_l: 'Standalone', zt_struct_iso_d: 'A free-standing building that doesn’t touch its neighbours.',
    zt_struct_jum_l: 'Semi-detached', zt_struct_jum_d: 'Shares one wall with the building next door.',
    zt_struct_con_l: 'Row-house', zt_struct_con_d: 'Attached on both sides in a row — usually the cheapest form to build (shared walls).',
    zt_intens_douce_l: 'gentle', zt_intens_douce_d: 'modest, incremental densification',
    zt_intens_inter_l: 'intermediate', zt_intens_inter_d: 'moderate densification is encouraged',
    zt_intens_high_l: 'high', zt_intens_high_d: 'the city is actively targeting densification here',
    zt_affect_res: 'primarily housing', zt_affect_mixte: 'mixed-use — housing alongside shops and services',
    zt_affect_cons: 'protected / conservation land', zt_affect_agri: 'agricultural',
    zt_affect_econ: 'employment / economic activity', zt_affect_div: 'diversified activity',
    zt_affect_recr: 'recreation and waterfront access', zt_affect_infra: 'major public infrastructure',
    zt_ex_title: 'How we got this number', zt_ex_s1_title: 'What’s built here today', zt_ex_s1_lead: 'This is a',
    zt_ex_s1_units: ', {n} {u}', zt_ex_s1_assumed: ' ({n} {u} assumed from the property type)', zt_unit: 'unit', zt_units: 'units',
    zt_ex_s2m_title: 'Its land-use designation',
    zt_ex_s2m_body: 'Under Montréal’s {plan}, this lot is in a {affect} area',
    zt_ex_s2m_intens: 'The plan sets urban intensification here to {level} — {desc}.',
    zt_ex_s3m_title: 'What the city plan targets',
    zt_ex_s3m_density: 'The plan sets a minimum average net density of {d} dwellings per hectare for this area. Montréal’s exact per-lot limits (height, units) are set by the borough zoning bylaw — this citywide layer shows the density the city is planning for.',
    zt_ex_s3m_nonres: 'This designation isn’t residential, so the plan sets no dwelling-density target here.',
    zt_ex_s2_title: 'Its zoning classification', zt_ex_s2_body: 'This lot sits in zone {zone}, category {cat}',
    zt_ex_s3_title: 'What the bylaw permits, and why', zt_ex_s3_intro: 'Per the Code de l’urbanisme{page}, this zone allows:',
    zt_ex_s3_page: ', page {p}', zt_ex_s3_title_alt: 'What the bylaw permits',
    zt_ex_s3_undecoded: 'Zone data is on record, but the specific permitted-use table for this category hasn’t been decoded yet — coverage is expanding category by category.',
    zt_ex_s4_title: 'The opportunity', zt_builtToday: 'built today', zt_plannedDensity: 'planned density', zt_ofUpside: '+{n} of upside',
    zt_ex_op_mtl_upside: 'The plan’s minimum density target of ~{d} dwellings/ha works out to about ~{n} {u} on this {lot} lot{official} — more than the {c} built today, signalling densification upside. A city planning target, not a per-lot permit; confirm exact limits with the borough.',
    zt_ex_op_mtl_none: 'This lot is already built at or above the city’s minimum density target{d}. Any further upside would come from the borough’s specific zoning bylaw (height, units) — not the citywide plan, which only sets a density floor.',
    zt_ex_op_nonres: 'This area is designated {affect} — not intended for residential development, so there’s no added-unit potential here.',
    zt_ex_op_mtl_nolot: 'This is a densification-friendly area — the plan targets ~{d} dwellings/ha{intens}. We don’t have this lot’s size on record yet, so we can’t estimate units, but the density target still signals the city wants more homes here.',
    zt_ex_op_insufficient_area: 'Not enough data to estimate development potential for this area yet.',
    zt_maxPermitted: 'max permitted', zt_zoningCapacity: 'zoning capacity',
    zt_ex_op_envelope: 'Estimated from the zoning envelope: a {lot} lot{official} × {cov}% coverage × {st} storeys. A theoretical maximum, not a permit.',
    zt_ex_op_cap: 'This zone caps residential buildings at {n} {u} regardless of lot size, so there’s {lim} added-unit potential here{sub}.',
    zt_limited: 'limited', zt_no: 'no', zt_ex_op_cap_sub: ' — value would come from a rebuild or subdivision, not more units',
    zt_realityCheck: 'Reality check:',
    zt_ex_assembly: 'this lot is small ({lot} sqft). A building near the zone’s full height would realistically need lot assembly with neighbouring properties — treat the figure as the zone’s capacity, not what fits on this lot alone.',
    zt_ex_contigu: 'Row-house/contiguous form is also permitted — usually cheaper to build.',
    zt_ex_alreadyBuilt: 'Already built at or near what zoning allows.',
    zt_ex_op_insufficient_zone: 'Not enough data to estimate development potential for this zone yet.',
    zt_dataAsOf: ' — data as of {ver}', zt_ex_indicative: 'Indicative only — confirm with the municipality before acting.',
    zt_officialRecord: 'official record', zt_densityParen: ' (~{d} dwellings/ha)', zt_intensParen: ' ({level} intensification)',
    zt_rb_title: 'Rebuild Calculator', zt_rb_sub: 'Every number is yours to change — plug in real quotes and rents', zt_rb_reset: 'Reset',
    zt_rb_unitsToBuild: 'Units to build', zt_rb_unitsHint: 'currently {current}, estimated potential {est}',
    zt_rb_unitSize: 'Avg. unit size', zt_rb_construction: 'Construction cost', zt_rb_demolition: 'Demolition cost',
    zt_rb_soft: 'Soft costs', zt_rb_softHint: 'design, permits, fees', zt_rb_contingency: 'Contingency', zt_rb_financing: 'Financing carry',
    zt_rb_rent: 'Rent per unit', zt_rb_rentHint: 'new construction often rents above old-stock average', zt_rb_capRate: 'Valuation cap rate',
    zt_rb_demo: 'Demolition', zt_rb_newConstruction: 'New construction ({n} sqft)', zt_rb_softCosts: 'Soft costs',
    zt_rb_financingCarry: 'Financing carry', zt_rb_totalCost: 'Total rebuild cost',
    zt_rb_totalInvestment: 'Total investment', zt_rb_totalInvestmentSub: 'purchase price + rebuild cost',
    zt_rb_projectedValue: 'Projected value', zt_rb_projectedValueSub: 'income approach, at your inputs',
    zt_rb_profit: 'Estimated profit at these numbers', zt_rb_loss: 'Estimated loss at these numbers',
    zt_rb_testHint: '— change any input to test your own assumptions',
    zt_rb_disclaimer: 'Nothing here is a quote or appraisal — it’s a calculator seeded with reasonable starting numbers. Replace them with a real contractor estimate and local rent data before acting on this.',
    zt_ct_agri: 'Agricultural zone (CPTAQ)', zt_ct_flood: 'Regulated flood zone', zt_ct_heritage: 'Heritage-protected',
    zt_dk_title: 'Development constraint — check before counting on any upside',
    zt_dk_title_plural: 'Development constraints — check before counting on any upside', zt_dk_source: 'official source',
    zt_floodRisk: 'Flood risk', zt_notOnRecord: 'not on record',
    zt_or_title: 'Official municipal records', zt_or_verified: 'Government-verified',
    zt_or_desc: 'From Quebec’s property assessment roll (rôle d’évaluation foncière) — the authoritative source for lot size and current dwelling count, independent of the listing.',
    zt_or_lotArea: 'Lot area', zt_or_dwellings: 'Current dwellings', zt_or_frontage: 'Frontage', zt_or_yearBuilt: 'Year built',
    zt_or_correction: 'Note: the listing implies {listed} {u}, but the official record shows {n} — worth verifying which is current.',
    zt_or_source: 'Source: Rôle d’évaluation foncière {year}', zt_or_officialData: 'official data',
    pp_multiSiteBanner: 'Same property listed on multiple sites',
    pp_backToProperties: 'Back to properties',
    pp_h_roi:           'Annual Average ROI',
    pp_h_costBreakdown: 'Annual Cost Breakdown',
    pp_h_costSub:       'Where each rental dollar goes',
    pp_h_scoreBreakdown:'Score Breakdown',
    pp_h_scoreSum:      'Sum of factor points (before risk adjustments)',
    pp_led_subtotal:    'Factor subtotal',
    pp_led_risk_critical:'Critical risk — capped',
    pp_led_risk_high2:  'Risk adjustment (2+ high-risk flags)',
    pp_led_risk_high1:  'Risk adjustment (1 high-risk flag)',
    pp_led_risk_medium: 'Risk adjustment (medium-risk flag)',
    pp_led_neighbourhood:'Neighbourhood adjustment',
    pp_led_income:      'Yield capped — rent estimated, not disclosed',
    pp_led_adjustment:  'Risk & market adjustment',
    pp_led_adjustmentNote:'The AI also weighs risk and neighbourhood context beyond the seven factors above.',
    pp_led_rounding:    'Rounding',
    pp_led_final:       'Score',
    pp_h_signals:       'Investment Signals',
    pp_h_priceVsMarket: 'Price vs Comparable Market',
    pp_col_metric:      'Metric',
    pp_col_total:       'Total',
    pp_viewAnalysis:    'View Property Analysis',
    pp_generateAnalysis:'Generate Property Analysis',
    pp_roi_cashflow:    'Cashflow',
    pp_roi_appreciation:'Appreciation',
    pp_roi_capitalization:'Capitalization',
    pp_cost_mortgage:   'Mortgage',
    pp_cost_schoolTax:  'School Tax',
    pp_cost_maintenance:'Maintenance',
    pp_cost_netIncome:  'Net Income',

    // Financing workbench (Financials tab)
    fw_analysis:        'Financing Analysis',
    fw_listingData:     'Listing data — Centris',
    fw_readOnly:        'Read-only',
    fw_askingPrice:     'Asking price',
    fw_grossRent:       'Gross rent',
    fw_municipalTax:    'Municipal tax',
    fw_schoolTax:       'School tax',
    fw_transferTaxLong: 'Transfer tax (droits de mutation)',
    fw_condoFees:       'Condo fees',
    fw_pricePerSqft:    'Price per sqft',
    fw_financingTerms:  'Financing terms',
    fw_offerPrice:      'Offer price',
    fw_downPayment:     'Down payment',
    fw_interestRate:    'Interest rate',
    fw_amortization:    'Amortization',
    fw_paymentFreq:     'Payment frequency',
    fw_monthly:         'Monthly',
    fw_biweekly:        'Bi-weekly',
    fw_weekly:          'Weekly',
    fw_operatingAssumptions: 'Operating assumptions',
    fw_editable:        'Editable',
    fw_grossRentNotListed: 'Gross rent (not on listing)',
    fw_vacancy:         'Vacancy allowance',
    fw_mgmtFee:         'Management fee',
    fw_insuranceYr:     'Insurance, per year',
    fw_maintPct:        'Maintenance, % of price',
    fw_mortgage:        'Mortgage',
    fw_transferTax:     'Transfer tax',
    fw_cashToClose:     'Cash required to close',
    fw_annualStatement: 'Annual operating statement',
    fw_grossIncome:     'Gross rental income',
    fw_insurance:       'Insurance',
    fw_noi:             'Net operating income',
    fw_cashFlowAnnual:  'Cash flow, annual',
    fw_keyRatios:       'Key ratios',
    fw_capRate:         'Cap rate',
    fw_coc:             'Cash-on-cash',
    fw_grm:             'GRM',
    fw_f_capRate:       'Net operating income ÷ purchase price',
    fw_f_coc:           'Annual cash flow ÷ cash required to close',
    fw_f_grm:           'Purchase price ÷ gross annual rent',
    fw_fromCentris:     'From the Centris listing — read-only',
    fw_fromCentrisShort:'From the Centris listing',
    fw_brokerAssumption:'Broker assumption — adjustable',
    fw_brokerAssumptionShort: 'Broker assumption',
    fw_footer:          "The transfer tax is Centris's own calculation for this property. Amounts in parentheses are deductions. Payments compound semi-annually per the Interest Act (RSC 1985, c I-15, s 6). For illustration only — verify rates and terms with the lender.",

    // Verdict compare
    vc_title:           'AI Verdict vs. Your Verdict',
    vc_vsAI:            'vs AI',
    vc_aiVerdict:       'AI Verdict',
    vc_aiSubtitle:      'AI weighting · listing terms',
    vc_yourVerdict:     'Your Verdict',
    vc_sub_live:        'your buy box · live',
    vc_sub_weights:     'your buy box',
    vc_sub_buybox:      'ranked against your buy box',
    vc_sub_mirror:      'mirrors AI until you set your buy box',
    vc_usingBuyBox:     'Scored against your buy-box targets.',
    vc_noBuyBox:        'Set your buy box in Settings to personalize this.',
    vc_noBuyBoxCalc:    'Set buy-box targets in Settings to see your personalized score break down here.',
    vc_fit_target:      'target',
    vc_badgeWeakest:    'weakest',
    vc_blendLine:       '65% average fit + 35% weakest factor',
    vc_usingCustom:     'Using your custom scoring criteria.',
    vc_usingDefPre:     'Using your',
    vc_usingDefPost:    'defaults — set your own in Settings.',
    vc_adjust:          'Adjust criteria',
    vc_howCalc:         'How is this calculated?',
    vc_hideCalc:        'Hide calculation',
    vc_colWeight:       'weight',
    vc_badgeTarget:     'your target',
    vc_badgeCapped:     'capped · est. rent',
    vc_ledSubtotal:     'Factor subtotal',
    vc_ledRounding:     'Rounding',
    vc_strat_hold:      'Buy & Hold',
    vc_strat_flip:      'Flip (Fix & Sell)',
    vc_strat_both:      'Buy & Hold + Flip',

    // Secondary pages (Compare, Saved, Reports, Saved Searches, Market Alerts)
    cmp_title:          'Property Comparison',
    cmp_empty:          'No properties to compare',
    cmp_emptyHint:      'Add properties from the Properties page to compare them side by side.',
    cmp_add:            'Add property',
    sav_empty:          'No saved properties yet',
    sav_emptyHint:      'Tap the bookmark on any property to save it here.',
    sav_remove:         'Remove from saved',
    rep_subtitle:       'Market insights across your coverage area',
    rep_scoreDistribution:'Score Distribution',
    rep_bestDeals:      'Best Deals',
    rep_biggestDiscounts:'Biggest Discounts',
    rep_activeMarkets:  'Active Markets',
    rep_noData:         'No data yet',
    ss_subtitle:        'Quick access to your frequent searches',
    ss_pinned:          'Pinned Searches',
    ss_quick:           'Quick Searches',
    ss_bookmarkHint:    'Bookmark searches you use often',
    ss_clickBookmark:   'Click the bookmark icon on any search to pin it here for quick access.',
    ma_subtitle:        'Track deals that match your criteria',
    ma_create:          'Create Alert',
    ma_basedOn:         'Alert me based on',
    ma_empty:           'No alerts yet',
    ma_emptyHint:       'Create alerts and get notified when great deals appear.',
    ma_proTips:         'Pro Tips',
    card_cashFlowMo:    'Cash Flow/mo',
    card_realDate:      'Real listing date from the source',
    card_trackedDate:   'Days since PlexAI first tracked this listing — this source hides the true list date',
  },
  fr: {
    // Nav
    dashboard:   'Tableau de bord',
    properties:  'Propriétés',
    watching:    'Surveillance',
    settings:    'Paramètres',
    logout:      'Déconnexion',

    // Stats cards
    propertiesInArea:  'Propriétés dans la zone',
    newToday:          'Nouvelles aujourd\'hui',
    strongOpps:        'Opportunités fortes',
    worthInvest:       'À examiner',
    priceDrops:        'Baisses de prix',
    avgScore:          'Score moyen',

    // Score categories
    strongOpportunity:  'Excellente opportunité',
    worthInvestigating: 'À examiner',
    marketPrice:        'Prix du marché',
    notRecommended:     'Non recommandé',

    // Actions
    viewAnalysis:       'Voir l\'analyse',
    watchProperty:      'Surveiller',
    reanalyze:          'Ré-analyser',
    backToProperties:   'Retour aux propriétés',
    viewOnSource:       'Voir sur',

    // Filters
    filters:       'Filtres',
    sortBy:        'Trier par',
    allTypes:      'Tous les types',
    allCities:     'Toutes les villes',
    minScore:      'Score min.',
    anyScore:      'Tout',
    gridView:      'Grille',
    listView:      'Liste',
    noResults:     'Aucune propriété ne correspond à vos filtres.',
    noResultsHint: 'Essayez d\'élargir votre zone ou votre gamme de prix.',

    // Detail page tabs
    aiBrief:      'Analyse IA',
    financials:   'Finances',
    comparables:  'Comparables',
    priceHistory: 'Historique des prix',
    sources:      'Sources',

    // Financial labels
    askingPrice:    'Prix demandé',
    marketValue:    'Valeur marchande (ventes comparables)',
    valueGap:       'Économies vs marché',
    discount:       'Sous le prix du marché',
    capRate:        'Rendement annuel (taux de cap.)',
    cashFlow:       'Profit mensuel (flux de trésorerie)',
    cashOnCash:     'Retour sur mise de fonds',
    noi:            'Revenu net annuel',
    grm:            'Ratio prix/loyer',
    downPayment:    'Votre mise de fonds (20%)',
    welcomeTax:     'Droits de mutation',
    monthlyMortgage:'Paiement hypothécaire mensuel',
    rentalIncome:   'Revenu locatif mensuel',
    grossIncome:    'Revenu brut annuel',
    municipalTax:   'Taxes municipales annuelles',
    schoolTax:      'Taxes scolaires annuelles',
    condoFees:      'Frais de condo mensuels',
    pricePerSqft:   'Prix / pi²',
    compsFound:     'Ventes comparables trouvées',

    // Misc
    units:       'unités',
    sqft:        'pi²',
    built:       'Bâti',
    daysOnMarket:'jours sur le marché',
    newBadge:    'NOUVEAU',
    priceDrop:   'Baisse de prix',
    active:      'Actif',
    topOpps:     'Meilleures opportunités',
    newListings: 'Nouvelles annonces',
    coverage:    'Couverture',
    viewAll:     'Voir tout →',
    notFound:    'Propriété introuvable',
    notFoundHint:'Cette annonce a peut-être été retirée.',
    browseAll:   'Parcourir toutes les propriétés →',
    queued:      'En attente',
    lastAnalyzed:'Dernière analyse',
    firstSeen:   'Première vue',
    lastChecked: 'Dernière vérification',
    mlsNumber:   'MLS#',
    noPriceHistory:   'Aucun changement de prix enregistré.',
    noComparables:    'Aucun comparable trouvé pour cette propriété.',
    noSources:        'Aucune source active enregistrée.',
    noAiBrief:        'Analyse IA non encore générée.',
    noAiBriefLow:     'Score sous 40 — analyse non générée pour cette propriété.',
    runPipeline:      'Cliquez sur Ré-analyser pour soumettre cette propriété.',
    dealProfile:      'Profil de l\'investissement',
    confidencePill:   'confiance',
    analyzedUsing:    'analysés',
    within:           'dans un rayon de',
    medianPrice:      'Prix médian',
    meanPrice:        'Prix moyen',
    pricedAt:         'Affiché à',
    belowMarket:      'sous le marché',
    aboveMarket:      'au-dessus du marché',
    originalListing:  'Mise en vente initiale',
    totalReduction:   'Réduction totale',
    fromOriginal:     'du prix initial',
    settings_title:   'Paramètres',
    settings_subtitle:'Gérez votre compte et vos préférences de notification.',
    settings_saved:   'Préférences enregistrées',

    // Multi-site comparison
    multiSite:        'Multi-site',
    multiSiteFilter:  'Multi-site seulement',
    lowestPrice:      'Prix le plus bas',
    lowestPriceSite:  'Site le moins cher',
    savingsVsHighest: 'Économie vs le plus haut',
    onSites:          'sites',
    priceComparison:  'Comparaison de prix',
    lastUpdated:      'Mis à jour',

    // Nav (sidebar)
    nav_marketAlerts:    'Alertes du marché',
    nav_savedSearches:   'Recherches enregistrées',
    nav_reports:         'Rapports',
    nav_savedProperties: 'Propriétés enregistrées',
    nav_adminDashboard:  'Tableau admin',

    // Settings — header
    set_headerSubtitle: 'Vos préférences d\'investissement, enregistrées sur votre compte.',
    set_applyToSearch:  'Appliquer à la recherche',
    set_save:           'Enregistrer',
    set_saved:          'Enregistré',
    set_saving:         'Enregistrement…',

    // Settings — search location
    set_location_title: 'Zone de recherche',
    set_location_desc:  'Les villes où vous cherchez — choisissez-en autant que vous voulez.',
    set_targetCities:   'Villes ciblées',
    set_addAnother:     'Ajouter une autre…',
    set_cityPlaceholder:'ex. Montréal, Laval…',
    set_add:            'Ajouter',
    set_searchRadius:   'Rayon de recherche',

    // Settings — budget
    set_budget_title:   'Fourchette de prix',
    set_budget_desc:    'La tranche de prix dans laquelle vous investissez.',
    set_budget_under:   'Moins de 300 k$',
    set_budget_300500:  '300 k$ – 500 k$',
    set_budget_500750:  '500 k$ – 750 k$',
    set_budget_7501m:   '750 k$ – 1 M$',
    set_budget_over1m:  'Plus de 1 M$',
    set_budget_custom:  'Personnalisé',
    set_minPrice:       'Prix min.',
    set_maxPrice:       'Prix max.',
    set_any:            'Tout',

    // Settings — property types
    set_types_title:    'Types de propriété',
    set_types_desc:     'Choisissez tous les types qui vous intéressent.',
    type_duplex:        'Duplex',
    type_triplex:       'Triplex',
    type_quadruplex:    'Quadruplex',
    type_quintuplex:    'Quintuplex+',
    type_single_family: 'Unifamiliale',
    type_condo:         'Condo',
    units_2:            '2 logements',
    units_3:            '3 logements',
    units_4:            '4 logements',
    units_5plus:        '5+ logements',
    unit_house:         'maison',
    unit_apartment:     'appartement',

    // Settings — investment goal
    set_goal_title:     'Objectif d\'investissement',
    set_goal_desc:      'Choisissez la stratégie (ou les deux) que vous utilisez.',
    goal_hold_label:    'Achat & conservation',
    goal_hold_desc:     'Revenus locatifs mensuels des locataires',
    goal_hold_info:     'Vous conservez la propriété à long terme et la louez. L\'objectif est un flux de trésorerie mensuel stable et une appréciation à long terme. Avec cette stratégie, Votre Verdict s\'appuie sur le taux de capitalisation et le flux de trésorerie.',
    goal_flip_label:    'Revente (rénover & vendre)',
    goal_flip_desc:     'Acheter bas, rénover, revendre avec profit',
    goal_flip_info:     'Vous achetez sous le marché, rénovez et revendez pour un profit ponctuel — l\'écart entre votre coût d\'achat plus les rénovations et le prix de revente. Avec cette stratégie, Votre Verdict s\'appuie sur le rabais et les jours sur le marché (vendeurs motivés).',
    set_whatsThis:      'C\'est quoi ?',
    set_useStarterNumbers: 'Utiliser des chiffres de départ',

    // Settings — alerts
    set_alerts_title:   'Déclencheurs d\'alerte',
    set_alerts_desc:    'Ce qui doit déclencher une notification.',
    set_newListings:    'Nouvelles annonces',
    set_newListings_sub:'Une propriété correspondant à vos critères apparaît',
    set_priceDrops:     'Baisses de prix',
    set_priceDrops_sub: 'Une annonce qui vous intéresse baisse de prix',
    set_minQuality:     'Qualité minimale',
    set_qualityAny:     'Tout',
    set_qualityGood:    'Bon',
    set_qualityTop:     'Élevé',
    set_qualityBest:    'Meilleur',

    // Settings — delivery
    set_delivery_title: 'Canaux de diffusion',
    set_delivery_desc:  'Comment vous joindre.',
    set_emailAlerts:    'Alertes courriel',
    set_sentTo:         'Envoyé à',
    set_sentToAccount:  'Envoyé au courriel de votre compte',
    set_smsWhatsapp:    'SMS et WhatsApp',
    set_comingSoon:     'Bientôt',
    set_phoneNumber:    'Numéro de téléphone',
    set_sms:            'SMS',
    set_sms_sub:        'Fonctionne sur tout téléphone',
    set_whatsapp:       'WhatsApp',
    set_whatsapp_sub:   'Messages enrichis avec photos',
    set_phoneNeeded:    'Entrez un numéro de téléphone valide pour activer SMS/WhatsApp.',

    // Settings — language
    set_language_title: 'Langue',
    set_language_desc:  'Langue de l\'interface.',

    // Settings — My Scoring Criteria
    set_scoring_title:  'Mes critères de notation',
    set_scoring_desc:   'Définissez votre buy box en chiffres réels. Les propriétés qui atteignent vos cibles sont affichées en premier et notées selon vos propres chiffres.',
    set_howThisWorks:   'Comment ça marche',
    set_yourBuyBox:     'Votre buy box',
    set_inNumbers:      '— en chiffres, pas en pourcentages',
    set_buyBoxHint:     'Définissez une cible avec le curseur ou en tapant un chiffre — laissez à « Désactivé » pour l\'ignorer. Une annonce qui atteint votre chiffre obtient un plein 100 sur ce facteur dans Votre Verdict, et plus elle s\'en approche, plus elle gagne de points. Ouvrez « Comment est-ce calculé ? » sur une propriété pour voir les points s\'additionner.',
    set_advanced:       'Avancé — ajustez le poids de chaque facteur dans le classement',
    set_reset:          'Réinitialiser',
    set_yourMix:        'Votre répartition',
    set_yourMix_desc:   'Chaque curseur est indépendant. Le beigne montre la part résultante de votre verdict.',
    set_topFactor:      'Facteur principal',
    set_off:            'Désactivé',
    preset_balanced:    'Équilibré',
    preset_cashflow:    'Flux de trésorerie',
    preset_buyhold:     'Achat & conservation',
    preset_value:       'Valeur / Revente',
    preset_custom:      'Personnalisé',
    factor_discount:    'Rabais sur prix',
    factor_cap_rate:    'Taux de cap.',
    factor_cash_flow:   'Flux de trésorerie',
    factor_grm:         'MRB',
    factor_confidence:  'Fiabilité',
    factor_dom_bonus:   'Jours affichés',
    factor_price_history:'Tendance de prix',
    factor_price_cut:   'Baisse de prix',
    fdesc_discount:     'À quel point le prix est sous les ventes comparables',
    fdesc_cap_rate:     'Rendement annuel — revenu net vs prix d\'achat',
    fdesc_cash_flow:    'Profit mensuel après hypothèque, taxes et dépenses',
    fdesc_grm:          'Prix par rapport au loyer brut (plus bas est mieux)',
    fdesc_confidence:   'À quel point les données comparables appuient les chiffres',
    fdesc_dom_bonus:    'Jours sur le marché — plus long = plus de levier vendeur',
    fdesc_price_cut:    'Baisse de prix depuis l\'affichage — signe d\'un vendeur motivé',
    // Scoring "how this works" modal
    help_intro:         'Votre Verdict classe chaque propriété selon vos chiffres plutôt que l\'opinion par défaut de l\'app. Ça fonctionne en trois étapes :',
    help_step1_title:   'Définissez vos cibles en chiffres réels',
    help_step2_title:   'Chaque annonce est notée selon vos chiffres',
    help_step3_title:   'Les facteurs se combinent en Votre Verdict',
    help_example:       'Exemple',
    help_note:          'Une protection : lorsque le loyer d\'une annonce est seulement estimé (non divulgué par le vendeur), les facteurs de revenu — taux de cap., flux de trésorerie, MRB — ne peuvent pas dépasser un score neutre, afin qu\'un loyer inventé ne gonfle pas un verdict.',
    help_step1_body:    'Utilisez les curseurs (ou tapez un chiffre) pour ce qui compte — p. ex. 200 $/mois de flux de trésorerie et 30+ jours sur le marché. Laissez le reste à Désactivé.',
    help_step2_body:    'Chaque facteur est noté de 0 à 100. Atteignez ou dépassez votre cible et il obtient 100 — plus une annonce dépasse votre chiffre, plus son score est élevé.',
    help_step3_body:    'Vos cibles (et tout ajustement d\'importance) se combinent en un seul score de 0 à 100, et toute la liste des propriétés est classée selon celui-ci — pas juste une page.',
    help_example_body:  'Une annonce à 250 $/mois (cible 200 $) affichée depuis 45 jours (cible 30) maximise les deux facteurs — elle se retrouve donc en haut de Votre Verdict.',

    // Dashboard
    dash_subtitle:      'Aperçu de l\'investissement immobilier au Québec',
    theme_light:        'Mode clair',
    theme_dark:         'Mode sombre',
    dash_greetMorning:  'Bonjour',
    dash_greetMorning2: 'Bien le bonjour',
    dash_greetAfternoon:'Bon après-midi',
    dash_greetAfternoon2:'J’espère que la journée va bien',
    dash_greetEvening:  'Bonsoir',
    dash_greetEvening2: 'Bonne soirée',
    dash_greetNight:    'Encore au travail',
    dash_greetNight2:   'Tard ce soir',
    dash_sub_new:       'nouvelles aujourd’hui',
    dash_sub_strong:    'achats forts',
    dash_newToday:      'Nouveau aujourd\'hui',
    dash_m_total:       'Total des propriétés',
    dash_m_total_sub:   'au Québec',
    dash_m_new:         'Nouvelles annonces',
    dash_m_new_sub:     'ajoutées aujourd\'hui',
    dash_m_great:       'Excellentes affaires',
    dash_m_great_sub:   'score 80+',
    dash_m_worth:       'À vérifier',
    dash_m_worth_sub:   'score 60–79',
    dash_m_drops:       'Baisses de prix',
    dash_m_drops_sub:   'depuis hier',
    dash_m_avg:         'Score moyen',
    dash_m_avg_sub:     'sur 100',
    dash_m_multi:       'Annonces multi-sites',
    dash_m_multi_sub:   'comparer les prix',
    dash_rankedYour:    'Classées selon vos propres critères',
    dash_bestNow:       'Meilleures opportunités d\'investissement en ce moment',
    dash_viewAll:       'Voir tout',
    dash_noScored:      'Aucune propriété notée pour l\'instant — lancez l\'analyse IA pour générer des scores.',
    dash_recentlyAdded: 'Récemment ajoutées à la base de données',
    dash_noNewToday:    'Aucune nouvelle annonce enregistrée aujourd\'hui.',
    analyze_title:          'Analyser une propriété',
    analyze_placeholder:    'Collez un lien Centris  ou  entrez une adresse complète…',
    analyze_cta:            'Analyser',
    analyze_hint:           'Nous la récupérons en direct et lançons l’analyse complète en une minute environ.',
    analyze_linkDetected:   'Lien',
    analyze_addressDetected:'Adresse',
    analyze_inYourDb:       'Déjà dans votre base de données',
    analyze_notListed:      'Absente ici? Nous la récupérons en direct.',
    analyze_recent:         'Vos recherches récentes',
    analyze_subtitle:       'Collez un lien Centris ou entrez une adresse — nous la récupérons en direct et l’évaluons selon vos critères.',
    analyze_placeholder_address: 'Entrez une adresse complète…  ex. 32 Rue des Érables, Saint-Sixte',
    analyze_placeholder_link:    'Collez un lien d’inscription Centris…',
    analyze_starting:       'Démarrage…',
    analyze_try:            'Essayez :',
    analyze_modal_title:    'Analyse de la propriété…',
    analyze_step_retrieving:'Récupération de l’inscription',
    analyze_step_analyzing: 'Analyse de la propriété',
    analyze_step_ready:     'Presque prêt',
    analyze_tip1:           'Récupération des données en direct depuis Centris.',
    analyze_tip2:           'Évaluation selon vos propres critères d’investissement.',
    analyze_tip3:           'Calcul des taxes, revenus et flux de trésorerie.',
    analyze_err_needsUrl_title:   'Adresse introuvable',
    analyze_err_needsUrl_body:    'Nous n’avons pas pu associer cette adresse à une inscription active. Collez plutôt le lien Centris.',
    analyze_err_unavailable_title:'Récupération temporairement indisponible',
    analyze_err_unavailable_body: 'Impossible de joindre l’inscription pour le moment — un problème temporaire, pas un souci avec la propriété. Réessayez sous peu.',
    analyze_err_notFound_title:   'Rien à analyser',
    analyze_err_failed_title:     'Échec de l’analyse',
    analyze_err_failed_body:      'Nous n’avons pas pu récupérer cette inscription. Vérifiez le lien et réessayez.',
    analyze_err_duproprio:        'DuProprio n’est pas encore pris en charge — essayez un lien Centris.',
    analyze_err_noScrapfly:       'La récupération n’est pas configurée sur ce serveur.',
    analyze_pasteLink:      'Coller un lien d’inscription',
    analyze_close:          'Fermer',
    analyze_freeUsed:       'analyses gratuites utilisées',
    analyze_limitTitle:     'Vous avez utilisé vos 10 analyses gratuites',
    analyze_limitBody:      'Passez à Pro pour des analyses illimitées partout au Québec.',
    analyze_proSoon:        'Forfait Pro — bientôt disponible',
    recent_title:       'Mes analyses récentes',
    recent_subtitle:    'Les propriétés que vous avez analysées, en un coup d’œil.',
    recent_capRate:     'Taux cap.',
    recent_cashflow:    'Trésorerie',
    recent_perMo:       '/mois',
    recent_viewReport:  'Voir le rapport complet',
    recent_justNow:     'à l’instant',
    recent_minAgo:      'min',
    recent_hrAgo:       'h',
    recent_dayAgo:      'j',
    recent_analyzedOn:  'Analysé',
    recent_price:       'Prix',
    recent_score:       'Score',
    recent_positive:    'Positif',
    recent_negative:    'Négatif',
    recent_delete:      'Retirer',
    pp_loading_title:   'Création de votre analyse…',
    pp_loading_sub:     'Calcul des chiffres et génération de votre rapport complet.',
    pp_step_fetch:      'Inscription',
    pp_step_score:      'Pointage',
    pp_step_render:     'Rapport',
    dash_quickFilters:  'Filtres rapides',
    dash_qf_new24:      'Nouveau (24 h)',
    dash_qf_best:       'Meilleures affaires (80+)',
    dash_qf_drops:      'Baisses de prix',
    dash_qf_multi:      'Sur plusieurs sites',
    dash_qf_yield:      'Rendement le plus élevé',
    dash_topCities:     'Villes principales',
    dash_covered:       'couvertes',
    dash_moreCities:    'autres villes',
    time_justNow:       'À l\'instant',
    time_hAgo:          'h',
    time_dAgo:          'j',

    // Properties page
    ptype_duplex:       'Duplex (2 logements)',
    ptype_triplex:      'Triplex (3 logements)',
    ptype_quadruplex:   'Quadruplex (4 logements)',
    ptype_quintuplex:   'Quintuplex+ (5+ logements)',
    ptype_single:       'Maison unifamiliale',
    ptype_condo:        'Condo',
    pf_category:        'Catégorie',
    category_residential: 'Résidentiel',
    category_commercial:  'Commercial',
    category_land:         'Terrain',
    pf_quality_any:     'Toute qualité',
    pf_quality_great:   'Excellentes affaires (80+)',
    pf_quality_worth:   'À vérifier (60+)',
    pf_quality_all:     'Tout afficher (40+)',
    pf_time_any:        'N\'importe quand',
    pf_time_24h:        'Dernières 24 h',
    pf_time_48h:        'Dernières 48 h',
    pf_time_7d:         'Derniers 7 jours',
    pf_time_30d:        'Derniers 30 jours',
    pf_sort_best:       'Meilleures affaires d\'abord',
    pf_sort_discount:   'Plus gros rabais d\'abord',
    pf_sort_priceasc:   'Prix le plus bas d\'abord',
    pf_sort_pricedesc:  'Prix le plus élevé d\'abord',
    pf_sort_newest:     'Plus récentes d\'abord',
    pf_sort_longest:    'Affichées le plus longtemps d\'abord',
    pf_chip_24h:        '24 h',
    pf_chip_48h:        '48 h',
    pf_chip_7d:         '7 jours',
    pf_chip_30d:        '30 jours',
    pf_chip_best:       'Meilleures affaires',
    pf_chip_discount:   'Plus gros rabais',
    pf_chip_lowest:     'Prix le plus bas',
    pf_chip_highest:    'Prix le plus élevé',
    pf_searchPlaceholder:'Rechercher une adresse ou une ville…',
    pf_mlsPlaceholder:  'Numéro MLS…',
    pf_egMin:           'ex. 300000',
    pf_egMax:           'ex. 1000000',
    pf_of:              'sur',
    pf_listingsMatch:   'annonces correspondent à vos critères',
    pf_rankAI:          'IA',
    pf_rankMine:        'Mes critères',
    pf_clear:           'Effacer',
    pf_clearAll:        'Tout effacer',
    pf_propertyType:    'Type de propriété',
    pf_minQuality:      'Qualité minimale',
    pf_listedWithin:    'Affichées depuis',
    pf_city:            'Ville',
    pf_minPrice:        'Prix min. ($)',
    pf_maxPrice:        'Prix max. ($)',
    pf_multiOnly:       'Affichées sur plusieurs sites',
    pf_sizeData:        'Données de superficie',
    pf_hasSqft:         'Avec superficie seulement',
    pf_floodRisk:       'Risque d\'inondation',
    pf_floodOnly:       'Zone inondable seulement',
    pf_noResults:       'Aucune propriété trouvée',
    pf_noResultsHint:   'Essayez d\'ajuster vos filtres ou d\'élargir la zone de recherche.',
    pf_noResultsHardHint: 'Votre buy box ne fait que classer les annonces — c\'est vide à cause de votre budget, type de propriété ou ville. Rien sur le marché ne correspond à cette combinaison. Essayez d\'en assouplir un :',
    pf_dropBudget:      'Retirer la limite de budget',
    pf_dropType:        'Tout type de propriété',
    pf_clearAllFilters: 'Effacer tous les filtres',
    pf_buyBoxTitle:     'Votre buy box',
    pf_buyBoxHint:      '— glissez ou tapez vos minimums; vide = désactivé',
    pf_daysNote:        'Les jours affichés comptent à partir de notre premier suivi — la plupart des sources masquent la vraie date d\'affichage.',
    pf_listingsFound:   'annonces trouvées',
    pf_loading:         'Chargement…',

    // Property page — verdict banner
    pp_verdict_strong:      'Achat fort',
    pp_verdict_strong_h:    'Cette propriété mérite une considération sérieuse de vos clients investisseurs.',
    pp_verdict_worth:       'À examiner',
    pp_verdict_worth_h:     'Bon potentiel — une vérification diligente approfondie est recommandée avant de vous engager.',
    pp_verdict_fair:        'Prix juste',
    pp_verdict_fair_h:      'Au prix du marché — rabais limité, potentiel limité à ce prix.',
    pp_verdict_not:         'Non recommandé',
    pp_verdict_not_h:       'Les défis l\'emportent sur l\'occasion au prix demandé actuel.',
    pp_m_capRate:           'Taux de cap.',
    pp_m_belowMarket:       'Sous le marché',
    pp_m_cashFlow:          'Flux de trésorerie mensuel',
    pp_m_grm:               'MRB',
    pp_m_noi:               'RNE annuel',
    pp_m_comparables:       'Comparables',
    pp_tapCard:             'Touchez une carte pour voir le calcul',
    // metric sub-badges
    pp_sub_aboveBench:  'Au-dessus du seuil',
    pp_sub_acceptable:  'Acceptable',
    pp_sub_belowFloor:  'Sous le plancher',
    pp_sub_bigDiscount: 'Gros rabais',
    pp_sub_modestDiscount: 'Rabais modeste',
    pp_sub_marketPrice: 'Prix du marché',
    pp_sub_aboveMarket: 'Au-dessus du marché',
    pp_sub_strongSurplus: 'Fort surplus',
    pp_sub_breakEven:   'Seuil de rentabilité',
    pp_sub_manageable:  'Gérable',
    pp_sub_topUp:       'Appoint requis',
    pp_sub_excellent:   'Excellent',
    pp_sub_elevated:    'Élevé',
    pp_sub_strongIncome:'Fort revenu',
    pp_sub_moderate:    'Modéré',
    pp_sub_thinMargin:  'Marge mince',
    pp_sub_negative:    'Négatif',
    pp_sub_highConf:    'Haute fiabilité',
    pp_sub_lowConf:     'Faible fiabilité',
    pp_sales:           'ventes',
    // calc panel
    pp_noData:          'Pas encore de données',
    pp_notEnoughComps:  'Pas assez de ventes comparables',
    pp_noRentalData:    'Aucune donnée de revenu locatif',
    pp_noComps:         'Aucune vente comparable trouvée',
    pp_howCalc:         'Comment c\'est calculé',
    pp_formula:         'Formule',
    pp_thisProperty:    'Cette propriété',
    pp_benchmarks:      'Repères',
    pp_mean_capRate:    'Cible : ≥6 % achat fort · ≥4,5 % acceptable · <4,5 % sous le plancher',
    pp_mean_below:      '≥10 % = gros rabais · ≥3 % = modeste · négatif = au-dessus du marché',
    pp_mean_cashFlow:   'Positif = autofinancé · Négatif = vous comblez chaque mois',
    pp_mean_grm:        '≤12x excellent · ≤15x acceptable · >15x cher par dollar de loyer',
    pp_mean_noi:        'Revenu net d\'exploitation — ce que l\'immeuble génère avant votre paiement de prêt',
    pp_mean_comps:      'Plus de comparables = plus de confiance dans la valeur marchande',
    // tabs + section headers + CTAs
    pp_tab_verdict:     'Verdict IA',
    pp_tab_comparables: 'Ventes comparables',
    pp_tab_zoning:      'Zonage',
    // Onglet zonage — accroche en langage clair, pastille d’honnêteté, liens de vérification, états vides
    pp_zh_plan_upside:   'Signal de développement — la Ville prévoit plus de logements ici qu’il n’en existe aujourd’hui. Il s’agit d’une estimation de planification urbaine, et non d’un permis propre au lot; confirmez la limite exacte auprès de l’arrondissement avant de vous y fier.',
    pp_zh_plan_none:     'Déjà bâti à peu près à la densité visée par le plan de la Ville. Tout potentiel additionnel viendrait du règlement de zonage de l’arrondissement, et non du plan à l’échelle de la ville.',
    pp_zh_lot_envelope:  'Ce lot pourrait accueillir plus de logements qu’aujourd’hui — une estimation à partir de l’enveloppe de zonage (superficie du lot × taux d’occupation × hauteur). À considérer comme une capacité à confirmer auprès de la Ville, non un permis garanti.',
    pp_zh_lot_permit:    'Le règlement de zonage permet ici plus de logements qu’il n’en existe aujourd’hui. Validez la grille auprès de la Ville, puis consultez l’économie de reconstruction ci-dessous.',
    pp_zh_lot_none:      'Déjà bâti à la limite ou près de ce que permet le zonage — potentiel d’ajout de logements limité. Les données financières et le calcul de reconstruction ci-dessous restent pertinents.',
    pp_zh_unknown:       'Nous ne pouvons pas encore estimer le potentiel d’ajout de logements pour ce lot — sa superficie ou les normes de la zone ne sont pas au dossier. Les données financières et les vérifications ci-dessous restent pertinentes.',
    pp_zh_today:         'aujourd’hui',
    pp_zh_potential:     'potentiel',
    pp_zoning_badge_plan:'Estimation du plan d’urbanisme',
    pp_zoning_verify_montreal:'Rechercher cette adresse sur la carte de zonage de Montréal',
    pp_zoning_verify_laval:'Ouvrir le règlement de zonage de Laval (PDF)',
    pp_zoning_verify_qc: 'Ouvrir la carte de zonage interactive de Québec',
    pp_zoning_verify_generic:'Vérifier sur le site officiel de la municipalité',
    pp_zoning_source_generic:'Vérifier ce lot sur la carte officielle de la municipalité',
    pp_zoning_empty_title_nc:'Aucune donnée de zonage pour l’instant',
    pp_zoning_empty_title_um:'Impossible de localiser ce lot',
    pp_zoning_empty_nc_b:' n’est pas encore couverte par nos données de zonage — nous couvrons actuellement Montréal et Laval, ville par ville. Tout le reste de cette propriété fonctionne quand même.',
    pp_zoning_empty_um_a:'Nous n’avons pas pu situer ce lot dans la couche de zonage de ',
    pp_zoning_empty_um_b:' — ses coordonnées tombent peut-être juste à l’extérieur d’une zone cartographiée. Tout le reste de cette propriété — pointage, finances et alertes — fonctionne quand même.',
    // Onglet zonage — traduction complète (mesures, explication, calculateur, registres, contraintes)
    zt_tab_title: 'Zonage et potentiel de développement',
    zt_badge_verified: 'Vérifié', zt_badge_partial: 'Données partielles', zt_badge_basic: 'Info de zone de base',
    zt_lotSqft: 'pi² du terrain', zt_official: 'officiel', zt_buildingSqft: 'pi² du bâtiment', zt_landUse: 'affectation', zt_zoneCode: 'code de zone',
    zt_tm_T1: 'Naturel — zones protégées ou à faible impact', zt_tm_T2: 'Agricole — périmètre agricole',
    zt_tm_T3: 'Banlieue — surtout unifamilial, faible densité', zt_tm_T4: 'Urbain — densification douce, jusqu’à ~2-3 étages',
    zt_tm_T5: 'Urbain compact — densité moyenne-élevée, jusqu’à 25 étages', zt_tm_T6: 'Centralité urbaine — zone de plus haute densité',
    zt_tm_CI: 'Institutionnel', zt_tm_ZC: 'Zone commerciale', zt_tm_ZE: 'Zone écologique', zt_tm_ZH: 'Zone résidentielle',
    zt_tm_ZI: 'Zone industrielle', zt_tm_ZM: 'Zone mixte', zt_tm_ZP: 'Zone de parc', zt_tm_SZD: 'Zone de développement spécial',
    zt_tier_1log_l: 'Un logement', zt_tier_1log_d: 'Une habitation sur le terrain — aucun potentiel d’ajout de logements ici à moins que la zone permette une catégorie supérieure.',
    zt_tier_2or3_l: '2–3 logements', zt_tier_2or3_d: 'Un duplex ou triplex : jusqu’à trois logements distincts dans un bâtiment.',
    zt_tier_4plus_l: '4+ logements', zt_tier_4plus_d: 'Un petit immeuble à logements — quatre logements ou plus. Le plafond exact dépend de la superficie du terrain, du taux d’occupation et des limites de hauteur.',
    zt_tier_h2_l: 'Duplex (H2)', zt_tier_h2_d: 'Un bâtiment résidentiel de deux logements.',
    zt_tier_h2c_l: 'Multilogement (H2)', zt_tier_h2c_d: 'Un type de bâtiment résidentiel à logements multiples.',
    zt_tier_h3_l: 'Triplex (H3)', zt_tier_h3_d: 'Un type de bâtiment de trois logements reconnu par le règlement.',
    zt_tier_h4_l: 'Immeuble 4+ logements (H4)', zt_tier_h4_d: 'Un bâtiment résidentiel de quatre logements ou plus.',
    zt_struct_iso_l: 'Isolé', zt_struct_iso_d: 'Un bâtiment autonome qui ne touche pas ses voisins.',
    zt_struct_jum_l: 'Jumelé', zt_struct_jum_d: 'Partage un mur avec le bâtiment voisin.',
    zt_struct_con_l: 'Contigu', zt_struct_con_d: 'Attaché des deux côtés en rangée — habituellement la forme la moins coûteuse à construire (murs partagés).',
    zt_intens_douce_l: 'douce', zt_intens_douce_d: 'densification modeste et progressive',
    zt_intens_inter_l: 'intermédiaire', zt_intens_inter_d: 'une densification modérée est encouragée',
    zt_intens_high_l: 'élevée', zt_intens_high_d: 'la ville vise activement la densification ici',
    zt_affect_res: 'principalement de l’habitation', zt_affect_mixte: 'usage mixte — habitation avec commerces et services',
    zt_affect_cons: 'terrain protégé / de conservation', zt_affect_agri: 'agricole',
    zt_affect_econ: 'emploi / activité économique', zt_affect_div: 'activité diversifiée',
    zt_affect_recr: 'récréation et accès aux rives', zt_affect_infra: 'grande infrastructure publique',
    zt_ex_title: 'Comment nous obtenons ce chiffre', zt_ex_s1_title: 'Ce qui est bâti aujourd’hui', zt_ex_s1_lead: 'Il s’agit d’un',
    zt_ex_s1_units: ', {n} {u}', zt_ex_s1_assumed: ' ({n} {u} présumé d’après le type de propriété)', zt_unit: 'logement', zt_units: 'logements',
    zt_ex_s2m_title: 'Sa désignation d’affectation',
    zt_ex_s2m_body: 'Selon le {plan} de Montréal, ce lot se trouve dans une zone {affect}',
    zt_ex_s2m_intens: 'Le plan fixe ici l’intensification urbaine à {level} — {desc}.',
    zt_ex_s3m_title: 'Ce que vise le plan de la ville',
    zt_ex_s3m_density: 'Le plan fixe une densité nette moyenne minimale de {d} logements par hectare pour ce secteur. Les limites exactes par lot à Montréal (hauteur, logements) sont fixées par le règlement de zonage de l’arrondissement — cette couche à l’échelle de la ville montre la densité que la ville prévoit.',
    zt_ex_s3m_nonres: 'Cette désignation n’est pas résidentielle; le plan ne fixe donc aucune cible de densité de logements ici.',
    zt_ex_s2_title: 'Sa classification de zonage', zt_ex_s2_body: 'Ce lot se situe dans la zone {zone}, catégorie {cat}',
    zt_ex_s3_title: 'Ce que le règlement permet, et pourquoi', zt_ex_s3_intro: 'Selon le Code de l’urbanisme{page}, cette zone permet :',
    zt_ex_s3_page: ', page {p}', zt_ex_s3_title_alt: 'Ce que le règlement permet',
    zt_ex_s3_undecoded: 'Les données de zone sont au dossier, mais la grille des usages permis pour cette catégorie n’a pas encore été décodée — la couverture s’étend catégorie par catégorie.',
    zt_ex_s4_title: 'L’occasion', zt_builtToday: 'bâti aujourd’hui', zt_plannedDensity: 'densité prévue', zt_ofUpside: '+{n} de potentiel',
    zt_ex_op_mtl_upside: 'La cible de densité minimale du plan de ~{d} logements/ha correspond à environ ~{n} {u} sur ce terrain de {lot}{official} — plus que les {c} bâtis aujourd’hui, ce qui signale un potentiel de densification. Une cible de planification municipale, pas un permis par lot; confirmez les limites exactes auprès de l’arrondissement.',
    zt_ex_op_mtl_none: 'Ce lot est déjà bâti à la cible de densité minimale de la ville ou au-delà{d}. Tout potentiel additionnel viendrait du règlement de zonage propre à l’arrondissement (hauteur, logements) — pas du plan à l’échelle de la ville, qui ne fixe qu’un plancher de densité.',
    zt_ex_op_nonres: 'Ce secteur est désigné {affect} — non destiné au développement résidentiel, donc aucun potentiel d’ajout de logements ici.',
    zt_ex_op_mtl_nolot: 'C’est un secteur propice à la densification — le plan vise ~{d} logements/ha{intens}. Nous n’avons pas encore la superficie de ce lot au dossier, donc nous ne pouvons pas estimer le nombre de logements, mais la cible de densité indique tout de même que la ville souhaite plus d’habitations ici.',
    zt_ex_op_insufficient_area: 'Pas assez de données pour estimer le potentiel de développement de ce secteur pour l’instant.',
    zt_maxPermitted: 'max permis', zt_zoningCapacity: 'capacité de zonage',
    zt_ex_op_envelope: 'Estimé à partir de l’enveloppe de zonage : un terrain de {lot}{official} × {cov} % d’occupation au sol × {st} étages. Un maximum théorique, pas un permis.',
    zt_ex_op_cap: 'Cette zone plafonne les bâtiments résidentiels à {n} {u} peu importe la taille du terrain; le potentiel d’ajout de logements ici est donc {lim}{sub}.',
    zt_limited: 'limité', zt_no: 'nul', zt_ex_op_cap_sub: ' — la valeur viendrait d’une reconstruction ou d’une subdivision, pas de logements supplémentaires',
    zt_realityCheck: 'Mise en contexte :',
    zt_ex_assembly: 'ce lot est petit ({lot} pi²). Un bâtiment proche de la pleine hauteur de la zone nécessiterait de façon réaliste un remembrement de lots avec les propriétés voisines — considérez ce chiffre comme la capacité de la zone, pas ce qui tient sur ce lot seul.',
    zt_ex_contigu: 'La forme contiguë (en rangée) est aussi permise — habituellement moins coûteuse à construire.',
    zt_ex_alreadyBuilt: 'Déjà bâti à la limite ou près de ce que permet le zonage.',
    zt_ex_op_insufficient_zone: 'Pas assez de données pour estimer le potentiel de développement de cette zone pour l’instant.',
    zt_dataAsOf: ' — données en date du {ver}', zt_ex_indicative: 'À titre indicatif seulement — confirmez auprès de la municipalité avant d’agir.',
    zt_officialRecord: 'donnée officielle', zt_densityParen: ' (~{d} logements/ha)', zt_intensParen: ' (intensification {level})',
    zt_rb_title: 'Calculateur de reconstruction', zt_rb_sub: 'Chaque chiffre est modifiable — entrez vos vrais devis et loyers', zt_rb_reset: 'Réinitialiser',
    zt_rb_unitsToBuild: 'Logements à construire', zt_rb_unitsHint: 'actuellement {current}, potentiel estimé {est}',
    zt_rb_unitSize: 'Taille moy. d’un logement', zt_rb_construction: 'Coût de construction', zt_rb_demolition: 'Coût de démolition',
    zt_rb_soft: 'Coûts indirects', zt_rb_softHint: 'conception, permis, honoraires', zt_rb_contingency: 'Imprévus', zt_rb_financing: 'Portage financier',
    zt_rb_rent: 'Loyer par logement', zt_rb_rentHint: 'la construction neuve se loue souvent au-dessus de la moyenne du parc ancien', zt_rb_capRate: 'Taux de capitalisation',
    zt_rb_demo: 'Démolition', zt_rb_newConstruction: 'Construction neuve ({n} pi²)', zt_rb_softCosts: 'Coûts indirects',
    zt_rb_financingCarry: 'Portage financier', zt_rb_totalCost: 'Coût total de reconstruction',
    zt_rb_totalInvestment: 'Investissement total', zt_rb_totalInvestmentSub: 'prix d’achat + coût de reconstruction',
    zt_rb_projectedValue: 'Valeur projetée', zt_rb_projectedValueSub: 'approche par le revenu, selon vos données',
    zt_rb_profit: 'Profit estimé selon ces chiffres', zt_rb_loss: 'Perte estimée selon ces chiffres',
    zt_rb_testHint: '— modifiez n’importe quelle donnée pour tester vos propres hypothèses',
    zt_rb_disclaimer: 'Rien ici n’est un devis ou une évaluation — c’est un calculateur alimenté par des valeurs de départ raisonnables. Remplacez-les par un vrai devis d’entrepreneur et des données de loyer locales avant d’agir.',
    zt_ct_agri: 'Zone agricole (CPTAQ)', zt_ct_flood: 'Zone inondable réglementée', zt_ct_heritage: 'Protégé au patrimoine',
    zt_dk_title: 'Contrainte de développement — à vérifier avant de compter sur tout potentiel',
    zt_dk_title_plural: 'Contraintes de développement — à vérifier avant de compter sur tout potentiel', zt_dk_source: 'source officielle',
    zt_floodRisk: 'Risque d’inondation', zt_notOnRecord: 'non au dossier',
    zt_or_title: 'Registres municipaux officiels', zt_or_verified: 'Vérifié par le gouvernement',
    zt_or_desc: 'Provient du rôle d’évaluation foncière du Québec — la source faisant autorité pour la superficie du terrain et le nombre de logements actuels, indépendamment de l’annonce.',
    zt_or_lotArea: 'Superficie du terrain', zt_or_dwellings: 'Logements actuels', zt_or_frontage: 'Façade', zt_or_yearBuilt: 'Année de construction',
    zt_or_correction: 'Note : l’annonce implique {listed} {u}, mais le registre officiel indique {n} — il vaut la peine de vérifier lequel est à jour.',
    zt_or_source: 'Source : Rôle d’évaluation foncière {year}', zt_or_officialData: 'données officielles',
    pp_multiSiteBanner: 'Même propriété affichée sur plusieurs sites',
    pp_backToProperties: 'Retour aux propriétés',
    pp_h_roi:           'RCI moyen annuel',
    pp_h_costBreakdown: 'Répartition des coûts annuels',
    pp_h_costSub:       'Où va chaque dollar de loyer',
    pp_h_scoreBreakdown:'Détail du score',
    pp_h_scoreSum:      'Somme des points des facteurs (avant ajustements de risque)',
    pp_led_subtotal:    'Sous-total des facteurs',
    pp_led_risk_critical:'Risque critique — plafonné',
    pp_led_risk_high2:  'Ajustement de risque (2+ signaux élevés)',
    pp_led_risk_high1:  'Ajustement de risque (1 signal élevé)',
    pp_led_risk_medium: 'Ajustement de risque (signal moyen)',
    pp_led_neighbourhood:'Ajustement du quartier',
    pp_led_income:      'Rendement plafonné — loyer estimé, non déclaré',
    pp_led_adjustment:  'Ajustement risque & marché',
    pp_led_adjustmentNote:'L\'IA tient aussi compte du risque et du contexte du quartier, au-delà des sept facteurs ci-dessus.',
    pp_led_rounding:    'Arrondi',
    pp_led_final:       'Score',
    pp_h_signals:       'Signaux d\'investissement',
    pp_h_priceVsMarket: 'Prix vs marché comparable',
    pp_col_metric:      'Métrique',
    pp_col_total:       'Total',
    pp_viewAnalysis:    'Voir l\'analyse de la propriété',
    pp_generateAnalysis:'Générer l\'analyse de la propriété',
    pp_roi_cashflow:    'Flux de trésorerie',
    pp_roi_appreciation:'Appréciation',
    pp_roi_capitalization:'Capitalisation',
    pp_cost_mortgage:   'Hypothèque',
    pp_cost_schoolTax:  'Taxe scolaire',
    pp_cost_maintenance:'Entretien',
    pp_cost_netIncome:  'Revenu net',

    // Financing workbench (Financials tab)
    fw_analysis:        'Analyse de financement',
    fw_listingData:     'Données de l\'annonce — Centris',
    fw_readOnly:        'Lecture seule',
    fw_askingPrice:     'Prix demandé',
    fw_grossRent:       'Loyer brut',
    fw_municipalTax:    'Taxe municipale',
    fw_schoolTax:       'Taxe scolaire',
    fw_transferTaxLong: 'Droits de mutation',
    fw_condoFees:       'Frais de condo',
    fw_pricePerSqft:    'Prix au pi²',
    fw_financingTerms:  'Conditions de financement',
    fw_offerPrice:      'Prix d\'offre',
    fw_downPayment:     'Mise de fonds',
    fw_interestRate:    'Taux d\'intérêt',
    fw_amortization:    'Amortissement',
    fw_paymentFreq:     'Fréquence de paiement',
    fw_monthly:         'Mensuel',
    fw_biweekly:        'Aux deux semaines',
    fw_weekly:          'Hebdomadaire',
    fw_operatingAssumptions: 'Hypothèses d\'exploitation',
    fw_editable:        'Modifiable',
    fw_grossRentNotListed: 'Loyer brut (absent de l\'annonce)',
    fw_vacancy:         'Provision pour vacance',
    fw_mgmtFee:         'Frais de gestion',
    fw_insuranceYr:     'Assurance, par année',
    fw_maintPct:        'Entretien, % du prix',
    fw_mortgage:        'Hypothèque',
    fw_transferTax:     'Droits de mutation',
    fw_cashToClose:     'Comptant requis à la clôture',
    fw_annualStatement: 'État d\'exploitation annuel',
    fw_grossIncome:     'Revenu locatif brut',
    fw_insurance:       'Assurance',
    fw_noi:             'Revenu net d\'exploitation',
    fw_cashFlowAnnual:  'Flux de trésorerie annuel',
    fw_keyRatios:       'Ratios clés',
    fw_capRate:         'Taux de cap.',
    fw_coc:             'Rendement du comptant',
    fw_grm:             'MRB',
    fw_f_capRate:       'Revenu net d\'exploitation ÷ prix d\'achat',
    fw_f_coc:           'Flux de trésorerie annuel ÷ comptant requis à la clôture',
    fw_f_grm:           'Prix d\'achat ÷ loyer annuel brut',
    fw_fromCentris:     'De l\'annonce Centris — lecture seule',
    fw_fromCentrisShort:'De l\'annonce Centris',
    fw_brokerAssumption:'Hypothèse du courtier — ajustable',
    fw_brokerAssumptionShort: 'Hypothèse du courtier',
    fw_footer:          'La taxe de mutation est le calcul de Centris pour cette propriété. Les montants entre parenthèses sont des déductions. Les paiements sont composés semestriellement selon la Loi sur l\'intérêt (LRC 1985, ch. I-15, art. 6). À titre indicatif seulement — vérifiez les taux et conditions avec le prêteur.',

    // Verdict compare
    vc_title:           'Verdict IA vs Votre Verdict',
    vc_vsAI:            'vs IA',
    vc_aiVerdict:       'Verdict IA',
    vc_aiSubtitle:      'Pondération IA · conditions de l\'annonce',
    vc_yourVerdict:     'Votre Verdict',
    vc_sub_live:        'votre buy box · en direct',
    vc_sub_weights:     'votre buy box',
    vc_sub_buybox:      'classé selon votre buy box',
    vc_sub_mirror:      'reflète l\'IA jusqu\'à ce que vous définissiez votre buy box',
    vc_usingBuyBox:     'Noté selon les cibles de votre buy box.',
    vc_noBuyBox:        'Définissez votre buy box dans Paramètres pour personnaliser ceci.',
    vc_noBuyBoxCalc:    'Définissez des cibles dans Paramètres pour voir votre score personnalisé se détailler ici.',
    vc_fit_target:      'cible',
    vc_badgeWeakest:    'plus faible',
    vc_blendLine:       '65 % ajustement moyen + 35 % facteur le plus faible',
    vc_usingCustom:     'Selon vos critères de notation personnalisés.',
    vc_usingDefPre:     'Selon vos réglages',
    vc_usingDefPost:    'par défaut — définissez les vôtres dans Paramètres.',
    vc_adjust:          'Ajuster les critères',
    vc_howCalc:         'Comment est-ce calculé ?',
    vc_hideCalc:        'Masquer le calcul',
    vc_colWeight:       'poids',
    vc_badgeTarget:     'votre cible',
    vc_badgeCapped:     'plafonné · loyer est.',
    vc_ledSubtotal:     'Sous-total des facteurs',
    vc_ledRounding:     'Arrondi',
    vc_strat_hold:      'Achat & conservation',
    vc_strat_flip:      'Revente (rénover & vendre)',
    vc_strat_both:      'Achat & conservation + Revente',

    // Secondary pages (Compare, Saved, Reports, Saved Searches, Market Alerts)
    cmp_title:          'Comparaison de propriétés',
    cmp_empty:          'Aucune propriété à comparer',
    cmp_emptyHint:      'Ajoutez des propriétés depuis la page Propriétés pour les comparer côte à côte.',
    cmp_add:            'Ajouter une propriété',
    sav_empty:          'Aucune propriété enregistrée',
    sav_emptyHint:      'Touchez le signet d\'une propriété pour l\'enregistrer ici.',
    sav_remove:         'Retirer des favoris',
    rep_subtitle:       'Aperçus du marché dans votre zone de couverture',
    rep_scoreDistribution:'Répartition des scores',
    rep_bestDeals:      'Meilleures affaires',
    rep_biggestDiscounts:'Plus gros rabais',
    rep_activeMarkets:  'Marchés actifs',
    rep_noData:         'Pas encore de données',
    ss_subtitle:        'Accès rapide à vos recherches fréquentes',
    ss_pinned:          'Recherches épinglées',
    ss_quick:           'Recherches rapides',
    ss_bookmarkHint:    'Ajoutez en favori les recherches que vous utilisez souvent',
    ss_clickBookmark:   'Cliquez sur l\'icône de signet d\'une recherche pour l\'épingler ici.',
    ma_subtitle:        'Suivez les affaires qui correspondent à vos critères',
    ma_create:          'Créer une alerte',
    ma_basedOn:         'M\'alerter selon',
    ma_empty:           'Aucune alerte pour l\'instant',
    ma_emptyHint:       'Créez des alertes et soyez averti quand de bonnes affaires apparaissent.',
    ma_proTips:         'Conseils',
    card_cashFlowMo:    'Flux/mois',
    card_realDate:      'Date d\'affichage réelle de la source',
    card_trackedDate:   'Jours depuis le premier suivi par PlexAI — cette source masque la vraie date d\'affichage',
  },
} as const

type LangKey = keyof typeof TRANSLATIONS['en']

export type { LangKey }

interface LanguageContextType {
  lang: 'en' | 'fr'
  setLang: (l: 'en' | 'fr') => void
  t: (key: string, vars?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | null>(null)

const LANG_KEY = 'quartis.lang'

function initialLang(): 'en' | 'fr' {
  try {
    const saved = localStorage.getItem(LANG_KEY)
    if (saved === 'en' || saved === 'fr') return saved
  } catch { /* ignore */ }
  return 'en'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<'en' | 'fr'>(initialLang)

  // Persist the choice so it survives reloads (previously reset to English).
  const setLang = (l: 'en' | 'fr') => {
    setLangState(l)
    try { localStorage.setItem(LANG_KEY, l) } catch { /* ignore */ }
  }

  const t = (key: string, vars?: Record<string, string | number>): string => {
    let s = (TRANSLATIONS[lang] as Record<string, string>)[key] ?? key
    if (vars) for (const k in vars) s = s.split(`{${k}}`).join(String(vars[k]))
    return s
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider')
  return ctx
}
