"""initial schema

Revision ID: 48962df77669
Revises: 
Create Date: 2026-06-01 12:27:23.787646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '48962df77669'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('location_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('location_radius_km', sa.Integer(), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('property_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('min_units', sa.Integer(), nullable=True),
    sa.Column('investment_strategy', sa.Enum('BUY_AND_HOLD', 'BUY_FIX_SELL', 'BOTH', name='investmentstrategy'), nullable=False),
    sa.Column('email_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_score_for_alert', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('FR', 'EN', name='language'), nullable=False),
    sa.Column('watched_property_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index('idx_brokers_location_center', 'brokers', ['location_center'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_brokers_email'), 'brokers', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mls_number', sa.String(length=50), nullable=True),
    sa.Column('address_hash', sa.String(length=64), nullable=True),
    sa.Column('full_address', sa.String(length=500), nullable=False),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('property_type', sa.Enum('DUPLEX', 'TRIPLEX', 'QUADRUPLEX', 'QUINTUPLEX_PLUS', 'SINGLE_FAMILY', 'CONDO', 'TOWNHOUSE', name='propertytype'), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('bedrooms_total', sa.Integer(), nullable=True),
    sa.Column('bathrooms_total', sa.Float(), nullable=True),
    sa.Column('sqft_total', sa.Integer(), nullable=True),
    sa.Column('lot_sqft', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PRICE_CHANGED', 'SOLD', 'DELISTED', 'EXPIRED', name='propertystatus'), nullable=False),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_source', sa.String(length=50), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rental_income_monthly', sa.Float(), nullable=True),
    sa.Column('municipal_taxes_annual', sa.Float(), nullable=True),
    sa.Column('school_taxes_annual', sa.Float(), nullable=True),
    sa.Column('condo_fees_monthly', sa.Float(), nullable=True),
    sa.Column('raw_expenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('needs_reanalysis', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_category', sa.Enum('STRONG_OPPORTUNITY', 'WORTH_INVESTIGATING', 'MARKET_PRICE', 'NOT_RECOMMENDED', name='scorecategory'), nullable=True),
    sa.Column('comparable_count', sa.Integer(), nullable=True),
    sa.Column('comparable_median_price', sa.Float(), nullable=True),
    sa.Column('comparable_mean_price', sa.Float(), nullable=True),
    sa.Column('value_gap', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('cap_rate', sa.Float(), nullable=True),
    sa.Column('noi_annual', sa.Float(), nullable=True),
    sa.Column('grm', sa.Float(), nullable=True),
    sa.Column('monthly_cash_flow', sa.Float(), nullable=True),
    sa.Column('cash_on_cash_return', sa.Float(), nullable=True),
    sa.Column('welcome_tax', sa.Float(), nullable=True),
    sa.Column('down_payment_20pct', sa.Float(), nullable=True),
    sa.Column('monthly_mortgage', sa.Float(), nullable=True),
    sa.Column('ai_brief_fr', sa.Text(), nullable=True),
    sa.Column('ai_brief_en', sa.Text(), nullable=True),
    sa.Column('analysis_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='analysisconfidence'), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_location', 'properties', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_properties_address_hash'), 'properties', ['address_hash'], unique=True)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index('ix_properties_city_score', 'properties', ['city', 'score'], unique=False)
    op.create_index(op.f('ix_properties_mls_number'), 'properties', ['mls_number'], unique=True)
    op.create_index('ix_properties_needs_reanalysis', 'properties', ['needs_reanalysis'], unique=False)
    op.create_index('ix_properties_score_status', 'properties', ['score', 'status'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index('ix_properties_type_status', 'properties', ['property_type', 'status'], unique=False)
    op.create_table('property_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('CENTRIS', 'REALTOR', 'DUPROPRIO', 'ROYALLEPAGE', 'ZOLO', 'ZOOCASA', 'HOUSESIGMA', name='scrapersource'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_at_scrape', sa.Float(), nullable=True),
    sa.Column('status_at_scrape', sa.String(length=50), nullable=True),
    sa.Column('changes_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_reanalysis', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_snapshots_property_id'), 'property_snapshots', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_snapshots_scraped_at'), 'property_snapshots', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_property_snapshots_source'), 'property_snapshots', ['source'], unique=False)
    op.create_table('property_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('CENTRIS', 'REALTOR', 'DUPROPRIO', 'ROYALLEPAGE', 'ZOLO', 'ZOOCASA', 'HOUSESIGMA', name='scrapersource'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_listing_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('has_price', sa.Boolean(), nullable=False),
    sa.Column('has_rental_income', sa.Boolean(), nullable=False),
    sa.Column('has_expenses', sa.Boolean(), nullable=False),
    sa.Column('has_photos', sa.Boolean(), nullable=False),
    sa.Column('has_sqft', sa.Boolean(), nullable=False),
    sa.Column('has_year_built', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'source', name='uq_property_source')
    )
    op.create_index(op.f('ix_property_sources_property_id'), 'property_sources', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_sources_property_id'), table_name='property_sources')
    op.drop_table('property_sources')
    op.drop_index(op.f('ix_property_snapshots_source'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_scraped_at'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_property_id'), table_name='property_snapshots')
    op.drop_table('property_snapshots')
    op.drop_index('ix_properties_type_status', table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index('ix_properties_score_status', table_name='properties')
    op.drop_index('ix_properties_needs_reanalysis', table_name='properties')
    op.drop_index(op.f('ix_properties_mls_number'), table_name='properties')
    op.drop_index('ix_properties_city_score', table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_address_hash'), table_name='properties')
    op.drop_index('idx_properties_location', table_name='properties', postgresql_using='gist')
    op.drop_table('properties')
    op.drop_index(op.f('ix_brokers_email'), table_name='brokers')
    op.drop_index('idx_brokers_location_center', table_name='brokers', postgresql_using='gist')
    op.drop_table('brokers')
    # ### end Alembic commands ###
