"""add_zoning_tables

Revision ID: 5145b8f4dfb9
Revises: db8b0e174b04
Create Date: 2026-07-21 09:16:07.093838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '5145b8f4dfb9'
down_revision: Union[str, None] = 'db8b0e174b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoning_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bylaw_reference', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'zone_code', name='uq_zoning_city_zone_code')
    )
    op.create_index('idx_zoning_zones_geometry', 'zoning_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_zoning_zones_city'), 'zoning_zones', ['city'], unique=False)
    op.create_index(op.f('ix_zoning_zones_is_active'), 'zoning_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_zoning_zones_zone_code'), 'zoning_zones', ['zone_code'], unique=False)
    op.create_table('zoning_zone_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('old_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zoning_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_zone_history_zone_id'), 'zoning_zone_history', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoning_zone_history_zone_id'), table_name='zoning_zone_history')
    op.drop_table('zoning_zone_history')
    op.drop_index(op.f('ix_zoning_zones_zone_code'), table_name='zoning_zones')
    op.drop_index(op.f('ix_zoning_zones_is_active'), table_name='zoning_zones')
    op.drop_index(op.f('ix_zoning_zones_city'), table_name='zoning_zones')
    op.drop_index('idx_zoning_zones_geometry', table_name='zoning_zones', postgresql_using='gist')
    op.drop_table('zoning_zones')
    # ### end Alembic commands ###
