"""add_rebuild_economics

Revision ID: 5861f27a487a
Revises: 895a45883884
Create Date: 2026-07-21 11:44:50.326415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '5861f27a487a'
down_revision: Union[str, None] = '895a45883884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rebuild_economics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'rebuild_economics')
    # ### end Alembic commands ###
