"""add_property_zoning_match

Revision ID: 895a45883884
Revises: 5145b8f4dfb9
Create Date: 2026-07-21 10:01:23.153820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '895a45883884'
down_revision: Union[str, None] = '5145b8f4dfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('zoning_zone_id', sa.UUID(), nullable=True))
    op.add_column('properties', sa.Column('zoning_matched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'properties', 'zoning_zones', ['zoning_zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'zoning_matched_at')
    op.drop_column('properties', 'zoning_zone_id')
    # ### end Alembic commands ###
