"""add_constraint_zones

Revision ID: 8c4819d1256d
Revises: b4677d03e016
Create Date: 2026-07-24 09:36:53.498617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '8c4819d1256d'
down_revision: Union[str, None] = 'b4677d03e016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('constraint_type', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constraint_zones_geometry', 'constraint_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_constraint_zones_city'), 'constraint_zones', ['city'], unique=False)
    op.create_index(op.f('ix_constraint_zones_constraint_type'), 'constraint_zones', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_constraint_zones_is_active'), 'constraint_zones', ['is_active'], unique=False)
    op.add_column('properties', sa.Column('development_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'development_constraints')
    op.drop_index(op.f('ix_constraint_zones_is_active'), table_name='constraint_zones')
    op.drop_index(op.f('ix_constraint_zones_constraint_type'), table_name='constraint_zones')
    op.drop_index(op.f('ix_constraint_zones_city'), table_name='constraint_zones')
    op.drop_index('idx_constraint_zones_geometry', table_name='constraint_zones', postgresql_using='gist')
    op.drop_table('constraint_zones')
    # ### end Alembic commands ###
