"""add_assessment_parcels

Revision ID: b4677d03e016
Revises: 006db69ca02f
Create Date: 2026-07-24 08:38:55.101395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'b4677d03e016'
down_revision: Union[str, None] = '006db69ca02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('match_key', sa.String(length=120), nullable=False),
    sa.Column('lot_area_m2', sa.Float(), nullable=True),
    sa.Column('num_dwellings', sa.Integer(), nullable=True),
    sa.Column('frontage_m', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('roll_year', sa.String(length=8), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'match_key', name='uq_assessment_city_key')
    )
    op.create_index('ix_assessment_city_key', 'assessment_parcels', ['city', 'match_key'], unique=False)
    op.create_index(op.f('ix_assessment_parcels_city'), 'assessment_parcels', ['city'], unique=False)
    op.create_index(op.f('ix_assessment_parcels_match_key'), 'assessment_parcels', ['match_key'], unique=False)
    op.add_column('properties', sa.Column('assessment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'assessment_data')
    op.drop_index(op.f('ix_assessment_parcels_match_key'), table_name='assessment_parcels')
    op.drop_index(op.f('ix_assessment_parcels_city'), table_name='assessment_parcels')
    op.drop_index('ix_assessment_city_key', table_name='assessment_parcels')
    op.drop_table('assessment_parcels')
    # ### end Alembic commands ###
