"""add verification pipeline

Revision ID: d0ad8508bfab
Revises: a1c5e8f3b9d2
Create Date: 2026-08-18 20:26:34.415162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'd0ad8508bfab'
down_revision: Union[str, None] = 'a1c5e8f3b9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_verification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('CENTRIS', 'REALTOR', 'REMAX', 'DUPROPRIO', 'ROYALLEPAGE', 'ZOLO', 'ZOOCASA', 'HOUSESIGMA', name='scrapersource', create_type=False), nullable=False),
    sa.Column('fields_checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.Enum('VERIFIED_MATCH', 'CORRECTED', 'MANUAL_REVIEW', 'FETCH_FAILED', 'NO_CENTRIS_MATCH', name='verificationoutcome'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_verification_log_outcome'), 'property_verification_log', ['outcome'], unique=False)
    op.create_index(op.f('ix_property_verification_log_property_id'), 'property_verification_log', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_verification_log_source'), 'property_verification_log', ['source'], unique=False)
    op.create_index(op.f('ix_property_verification_log_verified_at'), 'property_verification_log', ['verified_at'], unique=False)
    op.create_index('ix_verification_log_property_verified', 'property_verification_log', ['property_id', 'verified_at'], unique=False)
    op.add_column('properties', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_properties_last_verified_at', 'properties', ['last_verified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_properties_last_verified_at', table_name='properties')
    op.drop_column('properties', 'last_verified_at')
    op.drop_index('ix_verification_log_property_verified', table_name='property_verification_log')
    op.drop_index(op.f('ix_property_verification_log_verified_at'), table_name='property_verification_log')
    op.drop_index(op.f('ix_property_verification_log_source'), table_name='property_verification_log')
    op.drop_index(op.f('ix_property_verification_log_property_id'), table_name='property_verification_log')
    op.drop_index(op.f('ix_property_verification_log_outcome'), table_name='property_verification_log')
    op.drop_table('property_verification_log')
    # ### end Alembic commands ###
